import {GuardControls} from './guard-controls.js';
import {templeCue} from './temple-combat.js';
import {appendTempleMeter} from './temple-hud.js';
import {combatCue} from './combat-cues.js';
import {eliteSpec} from './realm-enemies.js';
import {PointerControls} from './pointer-controls.js';
import {combatFocus} from './combat-focus.js';
import {questGuidance} from './quest-guidance.js';
import {RIFT} from './kek-rift.js';
import {attackCue} from './attack-motion.js';
import {domainCue} from './domain-motion.js';
import {GUARDIAN_STYLE} from './enemy-motion.js';
import {createJournal} from './journal.js';
import {ITEMS,stats,useItem} from './systems.js';
import {SAVE_KEY,GROUND,WORLDS,createState,step,act,enterWorld,revive,snapshot,levelFor,maxHealth,canRelease,canRift,riftInput,canDomain,abilityReady,domainReady,DOMAIN} from './core.js';
import {loadArt,Renderer} from './render.js';
import {Sound} from './audio.js';
const storageKey=new URLSearchParams(location.search).get('practice')==='1'?'pepe-soul-world-practice-v1':SAVE_KEY;
const $=id=>document.getElementById(id),canvas=$('game');
let saved=null;try{saved=JSON.parse(localStorage.getItem(storageKey));}catch{}
const state=createState(saved),keys=new Set(),touchKeys=new PointerControls(),sound=new Sound();
const guardControls=new GuardControls(state.player,keys,touchKeys);
let journalOpen=false,journal,lastCheckpoint=0;
let begun=false,paused=false,ready=false,renderer,last=0,accumulator=0,toastUntil=0,lastUI=0,walkTarget=null,storageAvailable=true;
const actions={Space:'jump',KeyW:'jump',ArrowUp:'jump',KeyJ:'attack',KeyK:'dash',KeyL:'wave',KeyE:'interact',KeyR:'release',KeyF:'domain'};
function releaseInputs(){keys.clear();touchKeys.clear();walkTarget=null;guardControls.reset();}
function message(text){$('toast').textContent=text;$('toast').style.opacity='1';toastUntil=performance.now()+6500;}
function save(){try{localStorage.setItem(storageKey,JSON.stringify(snapshot(state)));$('save-state').textContent='Progress saved on this device';}catch{storageAvailable=false;$('save-state').textContent='Session only · storage unavailable';}}
function flush(){for(const e of state.events){renderer?.effect(e,state);sound.play(e.type);if(e.type==='gate')toggleJournal(true,'Map');if(e.type==='save')save();if(e.type==='message')message(e.text);if(e.type==='level')message(`Level ${e.level}. Your spirit grows stronger.`);if(e.type==='loot')message((e.item?ITEMS[e.item].name+' recovered · ':'')+(e.amount||0)+' spirit fragments');if(e.type==='death'){$('death-screen').hidden=false;$('revive').textContent=state.discoveries.includes(state.world)?'Return to the echo shrine →':'Return to Kek Academy →';releaseInputs();}if(e.type==='guardBlock')message('Sword block · '+e.cost+' Spirit');if(e.type==='guardBreak'){guardControls.latched=false;message('Guard broken · Release guard, then recover.');}if(e.type==='world'){releaseInputs();message(WORLDS.find(w=>w.id===e.world).subtitle);} }state.events.length=0;}
function setPaused(value){paused=value;releaseInputs();accumulator=0;$('pause-screen').hidden=!value;$('pause').textContent=value?'Resume':'Pause';$('pause').setAttribute('aria-pressed',String(value));if(!value)canvas.focus({preventScroll:true});}
function toggleJournal(value,name){if(value&&paused)return;if(!begun||!ready||state.dead)return;journalOpen=value;releaseInputs();accumulator=0;if(value){journal.open(name);save();}else{journal.close();canvas.focus({preventScroll:true});}}
function press(code,hold=true){if(!begun||!ready||paused||journalOpen||state.dead)return;if(hold)keys.add(code);guardControls.takeOver(code);guardControls.sync();if(actions[code]){act(state,actions[code]);flush();}}
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.code==='Escape'){if(journalOpen)toggleJournal(false);else if(begun)setPaused(!paused);return;}const journalKeys={Tab:'Map',KeyM:'Map',KeyQ:'Quests',KeyC:'Skills',KeyI:'Inventory',KeyG:'Gear'};if(journalKeys[e.code]&&!(e.code==='Tab'&&journalOpen)){e.preventDefault();toggleJournal(!journalOpen,journalKeys[e.code]);return;}if(e.code==='Digit1'||e.code==='Digit2'){if(begun&&!paused&&!journalOpen){useItem(state,e.code==='Digit1'?'healthFlask':'spiritFlask');flush();}return;}if(e.target instanceof HTMLButtonElement && (e.code==='Space'||e.code==='Enter'))return;if(actions[e.code]||['KeyA','KeyD','ArrowLeft','ArrowRight','KeyS','ArrowDown'].includes(e.code)){e.preventDefault();if(!e.repeat){walkTarget=null;press(e.code);}}});
window.addEventListener('keyup',e=>{keys.delete(e.code);guardControls.sync();});
window.addEventListener('blur',()=>{keys.clear();touchKeys.clear();if(begun && !state.dead)setPaused(true);});
document.addEventListener('visibilitychange',()=>{if(document.hidden && begun && !state.dead)setPaused(true);});
canvas.addEventListener('pointerdown',e=>{if(!begun||paused||journalOpen||state.dead)return;canvas.focus({preventScroll:true});const rect=canvas.getBoundingClientRect();const x=(e.clientX-rect.left)/rect.width*canvas.width+renderer.camera;const y=(e.clientY-rect.top)/rect.height*canvas.height-renderer.floorOffset;const enemy=state.enemies.find(en=>!en.dead && Math.abs(en.x-x)<85 && y>GROUND-250);if(enemy && Math.abs(enemy.x-state.player.x)<190){walkTarget=null;state.player.face=enemy.x>state.player.x?1:-1;act(state,'attack');flush();}else walkTarget=Math.max(100,Math.min(2500,x));});
for(const button of document.querySelectorAll('[data-item]'))button.addEventListener('click',()=>{if(begun&&ready&&!paused&&!journalOpen&&!state.dead){useItem(state,button.dataset.item);flush();}});
for(const button of document.querySelectorAll('[data-key]')){
  button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);walkTarget=null;touchKeys.hold(e.pointerId,button.dataset.key);press(button.dataset.key,false);});
  for(const name of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(name,e=>{touchKeys.release(e.pointerId);guardControls.sync();});
}
$('begin').disabled=true;$('begin').textContent='Painting your world…';
$('begin').addEventListener('click',()=>{if(!ready)return;begun=true;$('intro').hidden=true;canvas.focus({preventScroll:true});message(state.oath?'Your journey continues. Tab opens the Soul Journal. K performs Warp Step.':'Walk to Goribbit and press E. Click the ground to walk, or use A / D.');});
$('pause').addEventListener('click',()=>{if(begun)setPaused(!paused);});$('resume').addEventListener('click',()=>setPaused(false));
$('revive').addEventListener('click',()=>{revive(state);$('death-screen').hidden=true;setPaused(false);flush();canvas.focus({preventScroll:true});});
$('sound').addEventListener('click',()=>{sound.enable(!sound.enabled);$('sound').textContent=sound.enabled?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound.enabled));});
const warpStatus=document.createElement('span');warpStatus.id='warp-status';warpStatus.className='warp-status';document.querySelector('.viewport').append(warpStatus);
const combatReadout=document.createElement('div');combatReadout.id='combat-readout';combatReadout.className='combat-readout';combatReadout.hidden=true;document.querySelector('.viewport').append(combatReadout);
const launches=document.createElement('div');launches.className='journal-launch';for(const name of ['Map','Quests','Skills','Inventory','Gear']){const b=document.createElement('button');b.textContent=name;b.onclick=()=>toggleJournal(!journalOpen,name);launches.append(b);}document.querySelector('.viewport').append(launches);
const questStrip=document.createElement('div');questStrip.className='quest-strip';questStrip.append($('quest-copy'),$('xp-label'),$('xp'));document.querySelector('.viewport').append(questStrip);
journal=createJournal(state,()=>{flush();updateUI();},toggleJournal);document.querySelector('#journal header').append($('motion'));
function resize(){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;const scale=Math.min(1600,Math.max(1000,rect.width))/rect.width;canvas.width=Math.round(rect.width*scale);canvas.height=Math.round(rect.height*scale);if(renderer)renderer.camera=Math.max(0,Math.min(2600-canvas.width,renderer.camera));}new ResizeObserver(resize).observe(canvas);resize();
let reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function applyMotion(){document.body.classList.toggle('effects-reduced',reduced);if(renderer)renderer.reduced=reduced;$('motion').setAttribute('aria-pressed',String(reduced));$('motion').textContent=reduced?'Effects reduced':'Reduce effects';}
$('motion').addEventListener('click',()=>{reduced=!reduced;applyMotion();});applyMotion();
for(const w of WORLDS){const b=document.createElement('button');b.className='realm';b.dataset.world=w.id;b.style.backgroundImage=`url(assets/${w.art}.webp)`;const strong=document.createElement('strong');strong.textContent=w.name;const sub=document.createElement('small');sub.textContent=w.id==='academy'?'Home · training · restoration':w.boss;const sym=document.createElement('span');sym.className='symbol';sym.textContent=w.symbol;b.append(strong,sub,sym);b.addEventListener('click',()=>{if(!begun||paused)return;if(w.id===state.world)return;if(enterWorld(state,w.id)){flush();canvas.focus({preventScroll:true});}else message('Finish training, then walk right to the academy gate.');});$('realm-list').append(b);}
const domainButton=document.createElement('button');domainButton.className='domain-action';domainButton.onclick=()=>{press('KeyF');keys.delete('KeyF');};document.querySelector('.viewport').append(domainButton);
const guardButton=document.createElement('button');guardButton.className='guard-action';guardButton.title='Hold S or ↓ to guard, or click to toggle. Front attacks cost Spirit. Ground hazards and rear attacks bypass.';guardButton.onclick=()=>{if(!begun||paused||journalOpen||state.dead)return;guardControls.toggle();walkTarget=null;canvas.focus({preventScroll:true});};document.querySelector('.viewport').append(guardButton);
const castReadout=document.createElement('div');castReadout.className='domain-cast';castReadout.hidden=true;const castLabel=document.createElement('span'),castProgress=document.createElement('progress');castProgress.max=1;castProgress.setAttribute('aria-label','Kek Domain cast progress');castReadout.append(castLabel,castProgress);document.querySelector('.viewport').append(castReadout);
function updateUI(){const p=state.player,l=levelFor(state.xp),world=WORLDS.find(w=>w.id===state.world);$('world-label').textContent=world.name.toUpperCase()+(state.world!=='academy'?(state.world==='temple'?(state.zone==='arena'?' · INNER SANCTUARY':' · APPROACH'):state.zone==='arena'?' · GUARDIAN ARENA':state.zone==='approach2'?' · APPROACH II':' · APPROACH I'):'');$('rank').textContent=`${state.complete?'GUARDIAN':l.level>=3?'ADEPT':'INITIATE'} / LV. ${l.level}`;$('health').max=maxHealth(state);$('health').value=p.hp;$('health-number').textContent=Math.ceil(p.hp);$('spirit').max=stats(state).spirit;$('spirit').value=p.sp;$('spirit-number').textContent=Math.floor(p.sp);$('xp').max=l.need;$('xp').value=l.remaining;$('xp-label').textContent=`${l.remaining} / ${l.need} XP · LEVEL ${l.level}`;
  const gate=Math.abs(p.x-2250)<=200;for(const b of document.querySelectorAll('.realm')){b.classList.toggle('active',b.dataset.world===state.world);b.setAttribute('aria-current',b.dataset.world===state.world?'location':'false');b.disabled=!begun||paused||state.dead||b.dataset.world===state.world||(b.dataset.world==='academy'&&state.zone==='arena'&&(!state.guardianDefeated||!gate))||(b.dataset.world!=='academy' && (state.world!=='academy'||!gate||state.training<3||!state.oath));}
  for(const [i,id] of ['frozen','crimson','void'].entries())$('seals').children[i].classList.toggle('collected',state.seals.includes(id));
  const guidance=questGuidance(state);$('quest-copy').textContent=guidance.text;const questLaunch=launches.querySelectorAll('button')[1];questLaunch.textContent=guidance.ready?'Quests · '+guidance.ready:'Quests';
  $('weapon').textContent=ITEMS[state.equipped.weapon].name+(p.release>0?' · Awakened':'');$('release-label').classList.toggle('active',canRelease(state));$('blade-copy').textContent=canRelease(state)?'R · Awaken for 8 seconds. Costs 55 spirit. Your cuts carry the oath.':'Reach level 3 and recover a seal to awaken your blade.';
  let hint='';if(state.world==='academy'){if(Math.abs(p.x-490)<180)hint='E · Speak to Master Goribbit';else if(Math.abs(p.x-870)<185)hint='J · Practice your sword cuts';else if(gate)hint=state.training===3?'M · Choose a realm':'Train at the academy first';}else if(state.zone==='arena')hint=state.guardianDefeated&&Math.abs(p.x-2250)<=200?'E · Return portal':'';else if(Math.abs(p.x-2250)<=200)hint=state.enemies.every(e=>e.dead)?(state.zone==='approach2'||state.world==='temple'?'E · Enter guardian arena':'E · Enter Approach II'):'Clear the approach first';else if(Math.abs(p.x-1360)<170)hint=state.discoveries.includes(state.world)?'Echo shrine · checkpoint attuned':'E · Attune to the echo shrine';else if(p.x<470)hint='E · Return to Kek Academy';$('interaction').textContent=hint;
  const {foe,others}=combatFocus(state.enemies,p,state.world);$('combat-readout').hidden=!foe;if(foe){$('combat-readout').replaceChildren();const name=document.createElement('strong');name.textContent=foe.boss?world.boss:eliteSpec(foe)?.name||world.enemy;const bar=document.createElement('progress');bar.max=foe.maxHp;bar.value=foe.hp;const cue=document.createElement('span');cue.textContent=((foe.world==='temple'?templeCue(foe):null)||(foe.mode==='windup'?(foe.boss&&foe.attackCount%2===1?GUARDIAN_STYLE[foe.world].wave+' · Jump or Warp through':(eliteSpec(foe)?eliteSpec(foe).cue+' · Jump or Warp away':'Incoming cut · Warp past the blade')):foe.mode==='recover'?'Recovery · opening for a cut':'J · cut / L · wave'))+' · '+foe.hp+' / '+foe.maxHp+' HP'+(others?' · +'+others+' nearby':'');$('combat-readout').append(name,bar,cue);if(foe.world==='temple')appendTempleMeter(combatReadout,foe);}
  castReadout.hidden=!p.domain;if(p.domain){const cue=domainCue(p.domain.elapsed);castLabel.textContent='KEK DOMAIN · '+cue.label.toUpperCase();castProgress.value=cue.progress;}
  domainButton.disabled=!begun||paused||journalOpen||!domainReady(state);domainButton.textContent=!canDomain(state)?'Kek Domain · Complete the oath':p.domain?'KEK DOMAIN · Manifesting':p.domainCooldown>0?'F · Kek Domain · '+Math.ceil(p.domainCooldown)+'s':'F · Kek Domain · 80 SP';
  $('warp-status').textContent=combatCue(state);
  guardButton.textContent=p.guardBroken>0?'Guard broken':p.guarding?'Sword guard · Release':guardControls.latched?'Guard queued · Cancel':'S · Sword guard';guardButton.setAttribute('aria-pressed',String(!!p.guarding||guardControls.latched));guardButton.disabled=!begun||paused||journalOpen||state.dead;
  const touchGuard=document.querySelector('[data-key="KeyS"]');touchGuard.setAttribute('aria-pressed',String(!!p.guarding));touchGuard.textContent=p.guarding?'Guarding':'Hold guard';touchGuard.disabled=!begun||paused||journalOpen||state.dead;
  for(const button of document.querySelectorAll('[data-item]')){const id=button.dataset.item,item=ITEMS[id],count=state.inventory[id]||0,full=item.heal?p.hp>=stats(state).health:p.sp>=stats(state).spirit;button.textContent=(item.heal?'Heal':'Spirit')+' ×'+count;button.disabled=!begun||paused||journalOpen||state.dead||count===0||full;button.title=count===0?'No flasks remaining':full?'Already full':item.description;}
  for(const [key,action,name,cooldown,cost] of [['KeyK','dash','Warp Step',p.dashCooldown,stats(state).warpCost],['KeyL','wave','Kek Wave',p.waveCooldown,28],['KeyR','release','Release',p.releaseCooldown,55]]){
   const button=document.querySelector(`[data-key="${key}"]`);button.disabled=!begun||paused||journalOpen||!abilityReady(state,action);
   const airRift=action==='wave'&&riftInput(state);
   if(airRift){button.textContent=p.riftCooldown>0?'Rift '+p.riftCooldown.toFixed(1)+'s':'Kek Rift';button.title=RIFT.cost+' SP · Jump + L';continue;}
   button.textContent=action==='release'&&p.release>0?'Awakened '+Math.ceil(p.release)+'s':cooldown>0?name+' '+cooldown.toFixed(1)+'s':name;
   button.title=action==='release'&&!canRelease(state)?'Reach level 3 and recover a seal':cooldown>0?'Recovering':p.sp<cost?'Requires '+cost+' SP':!abilityReady(state,action)?'Finish combat recovery':cost+' SP';
  }
  const touchDomain=document.querySelector('[data-key="KeyF"]');touchDomain.disabled=domainButton.disabled;touchDomain.textContent=p.domain?'Casting':p.domainCooldown>0?'Domain '+Math.ceil(p.domainCooldown)+'s':'Domain';touchDomain.title=canDomain(state)?'Requires grounded recovery and 80 SP':'Complete the three-seal oath';
  canvas.setAttribute('aria-label',`${world.name}. ${state.zone}. Crown Pepe at ${Math.round(p.x)}, ${p.y<GROUND-1?'airborne':p.mode}. HP ${Math.ceil(p.hp)}. Level ${l.level}. Training ${state.training} of 3. Seals ${state.seals.length} of 3.`);
}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(ready){if(begun&&!paused&&!journalOpen&&!state.dead){accumulator+=dt;if(renderer.freeze>0){accumulator=0;}else{while(accumulator>=1/60){const p=state.player;if(walkTarget!==null && Math.abs(walkTarget-p.x)<10)walkTarget=null;const left=keys.has('KeyA')||keys.has('ArrowLeft')||touchKeys.has('KeyA')||(walkTarget!==null && walkTarget<p.x),right=keys.has('KeyD')||keys.has('ArrowRight')||touchKeys.has('KeyD')||(walkTarget!==null && walkTarget>p.x);step(state,{left,right,guard:guardControls.held},1/60);accumulator-=1/60;flush();if(state.dead)break;}}renderer.update(dt,state);}else if(!begun){state.time+=dt;}renderer.draw(state);if(begun&&!state.dead&&now-lastCheckpoint>5000){save();lastCheckpoint=now;}if(now-lastUI>100){updateUI();lastUI=now;}if(now>toastUntil)$('toast').style.opacity='.15';}requestAnimationFrame(frame);}
try{const art=await loadArt();renderer=new Renderer(canvas,art);applyMotion();ready=true;$('begin').disabled=false;$('begin').innerHTML='Enter Kek Academy <span>→</span>';updateUI();requestAnimationFrame(frame);}catch(error){console.error(error);$('begin').textContent='Artwork could not load';message('An artwork file could not load. Reload after the assets finish downloading.');$('save-state').textContent='Preview loading failed';}
window.addEventListener('pagehide',()=>{if(begun && storageAvailable)save();});
