import {RIFT} from './kek-rift.js';
import {questGuidance} from './quest-guidance.js';
import {ITEMS,SKILLS,QUESTS,stats,compareGear,skillPreview,skillPoints,equip,learn,useItem,claimQuest,questReady,atMentor,buyItem,upgradeGear} from './systems.js';
import {WORLDS,enterWorld,enterArena,approachRemaining,levelFor,DOMAIN,canDomain,canRift} from './core.js';
export function createJournal(state,changed,toggle){
 const panel=document.createElement('section');panel.id='journal';panel.hidden=true;panel.setAttribute('aria-label','Soul journal');panel.innerHTML='<header><div><small>CROWN’S JOURNEY</small><h2>Soul journal</h2></div><a href="animation.html">Motion studio ↗</a><button id="close-journal">Close · Esc</button></header><nav></nav><div class="journal-content"></div>';document.querySelector('.viewport').append(panel);
 let tab='Map';const content=panel.querySelector('.journal-content'),nav=panel.querySelector('nav');
 for(const name of ['Map','Quests','Skills','Inventory','Gear']){const b=document.createElement('button');b.textContent=name;b.onclick=()=>{tab=name;render();};nav.append(b);}
 panel.querySelector('#close-journal').onclick=()=>toggle(false);
 function icon(id){const i=ITEMS[id].icon;return `<span class="item-icon" style="background-position:${i%4/3*100}% ${Math.floor(i/4)/2*100}%"></span>`;}
 function button(text,fn,disabled=false){const b=document.createElement('button');b.textContent=text;b.disabled=disabled;b.onclick=()=>{fn();changed();render();};return b;}
 function card(html){const c=document.createElement('article');c.innerHTML=html;content.append(c);return c;}
 function comparison(id){const preview=compareGear(state,id);if(!preview)return '';const labels={attack:'Sword bonus',health:'Maximum HP',defense:'Defense',regen:'Spirit / second',warpRange:'Warp reach',wave:'Wave damage'};if(preview.current===id)return '<p class="gear-comparison">Currently equipped</p>';const entries=Object.entries(preview.changes);return `<div class="gear-comparison"><small>VERSUS ${ITEMS[preview.current].name.toUpperCase()}</small>${entries.length?entries.map(([key,delta])=>`<p class="${delta>0?'gear-gain':'gear-loss'}">${labels[key]} ${delta>0?'+':''}${delta} → ${preview.after[key]}</p>`).join(''):'<p>Same combat stats</p>'}${preview.after.health<state.player.hp?'<p>Equipping lowers your current HP to the new maximum.</p>':''}</div>`;}
 function render(){nav.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.textContent===tab));content.replaceChildren();const st=stats(state),level=levelFor(state.xp).level;
 const summary=document.createElement('p');summary.className='journal-summary';summary.textContent=`Level ${level} · ${state.fragments} spirit fragments · ${skillPoints(state)} skill points`;content.append(summary);
 if(tab==='Map'){
 const w=WORLDS.find(w=>w.id===state.world);card(`<h3>${w.name}</h3><p>${w.subtitle}</p><div class="route"><span>Gate / mentor</span><span>Training / enemies</span><span>Shrine</span><span>Guardian passage</span><i style="left:${state.player.x/2600*100}%">◆</i></div><p>◆ Crown’s position · ${Math.round(state.player.x)} / 2600</p><p>${state.world==='academy'?'Goribbit 490 · Effigy 870 · Veil Gate 2250':state.zone==='arena'?'Guardian starts at 2070 · Return portal 2250 (opens on defeat)':'Return gate 230 · Enemies 800 / 1160 / 1540 · Shrine 1360 · Passage 2250'}</p>`);
 for(const world of WORLDS){
 const current=world.id===state.world,academy=world.id==='academy',arena=state.zone==='arena',returnLocked=arena&&(!state.guardianDefeated||Math.abs(state.player.x-2250)>200);
 const reason=world.id==='temple'&&!state.complete?'Complete the three-seal oath to enter Emerald Temple':current?'You are here':state.dead?'Revive to travel':academy?(returnLocked?(state.guardianDefeated?'Reach the open return portal at 2250':'Defeat the guardian to open its return portal'):'Return to Goribbit'):state.world!=='academy'?'Return to Kek Academy first':!state.oath?'Accept Goribbit’s oath first':state.training<3?'Land three cuts on the academy effigy':Math.abs(state.player.x-2250)>200?'Reach the academy veil gate at 2250':'Ready to cross the veil';
 const locked=current||state.dead||(academy&&returnLocked)||(!academy&&(world.id==='temple'&&!state.complete||state.world!=='academy'||!state.oath||state.training<3||Math.abs(state.player.x-2250)>200));
 const c=card(`<div class="map-art" style="background-image:url(assets/${world.art}.webp)"></div><h3>${world.name}</h3><p>${academy?'Train, restore, buy flasks and temper your blade.':world.boss}</p>${academy?'<p>Oath '+(state.oath?'accepted':'awaiting Goribbit')+' · Training '+state.training+' / 3</p>':'<div class="gear-comparison"><p>'+ (world.id==='temple'?'Temple challenge · '+(state.bossRewards.includes('temple')?'Completed':'Unfinished'):'Seal · '+(state.seals.includes(world.id)?'Recovered':'Still missing'))+'</p><p>Shrine · '+(state.discoveries.includes(world.id)?'Attuned':'Undiscovered')+'</p><p>Guardian reward · '+(state.bossRewards.includes(world.id)?'Recovered':'Not recovered')+'</p></div>'}<p>${reason}</p>`);
 c.append(button(current?'You are here':academy?'Return to Academy':'Travel to '+world.name,()=>{if(enterWorld(state,world.id))toggle(false);},locked));
 }
 if(state.world!=='academy'){const arena=state.zone==='arena',remaining=approachRemaining(state),c=card('<h3>'+(state.world==='temple'?(arena?'Inner Sanctuary':'Temple Approach'):arena?'Guardian arena':state.zone==='approach2'?'Approach II · Elite patrol':'Approach I · Outer patrol')+'</h3><p>'+(state.world==='temple'?questGuidance(state).text:arena?'Defeat the guardian, collect your rewards, then use the portal at 2250.':remaining+' / 3 enemies remain. Clear them, then reach the passage at 2250.')+'</p>');if(!arena)c.append(button(state.zone==='approach2'||state.world==='temple'?'Enter guardian arena':'Enter Approach II',()=>{if(enterArena(state))toggle(false);},remaining>0||Math.abs(state.player.x-2250)>200||state.dead));}card('<h3>Crossing the veil</h3><p>Enemy realms are reached from the academy veil gate. Emerald Temple opens after your completed oath and has one approach leading directly to its guardian. The other realms have an outer patrol, an elite approach, and a third map for its guardian. Returning to the academy restores health and spirit; recovered seals, gear and shrine attunements stay saved.</p>');
 }else if(tab==='Quests'){
 const ready=QUESTS.filter(q=>questReady(state,q));
 card(`<h3>${ready.length?ready.length+' reward'+(ready.length===1?'':'s')+' ready to claim':'Your next oath'}</h3><p>${ready.length?'Claim the completed quests below. Gear rewards enter your inventory; equip them in Gear or Inventory.':'Follow an unfinished quest below. Rewards stay available until you claim them.'}</p>`);
 const ordered=[...QUESTS].sort((a,b)=>Number(questReady(state,b))-Number(questReady(state,a))||Number(state.claimedQuests.includes(a.id))-Number(state.claimedQuests.includes(b.id)));
 for(const q of ordered){const claimed=state.claimedQuests.includes(q.id),ready=questReady(state,q),c=card(`<small>${claimed?'REWARD RECEIVED':ready?'READY TO CLAIM':'IN PROGRESS'}</small><h3>${q.name}</h3><p>${q.description}</p><progress max="${q.need}" value="${q.progress(state)}"></progress><p>${Math.min(q.need,q.progress(state))} / ${q.need} · ${q.xp} XP · ${q.fragments} fragments${q.item?' · '+ITEMS[q.item].name:''}</p>`);c.append(button(claimed?'Completed':ready?'Claim reward':'Quest unfinished',()=>claimQuest(state,q.id),!ready));if(claimed&&q.item)c.append(button('View reward in Inventory',()=>{tab='Inventory';}));}
 if(state.bossRewards.length){const c=card('<h3>Guardian spoils recovered</h3><p>'+state.bossRewards.map(id=>WORLDS.find(w=>w.id===id)?.name).join(' · ')+'</p><p>Your recovered guardian blades are in your inventory. Compare and equip them before the next crossing.</p>');c.append(button('Open Inventory',()=>{tab='Inventory';}));}
 }
 else if(tab==='Skills'){card('<h3>KEK WAVE · Sword release</h3><p>L releases a travelling emerald crescent. It pierces enemies, striking each once. Move or Warp after firing to reposition.</p><p>28 SP · 1.2s cooldown · Damage '+(36+levelFor(state.xp).level*3+stats(state).wave)+'</p><p>Wave ranks extend its flight; gear can add damage. After unlocking Kek Rift, airborne L becomes the committed sword slam.</p>');card('<h3>KEK RIFT · Sword technique</h3><p>'+(canRift(state)?'Unlocked · Jump + L to slam. Quick follow-up inputs are buffered during lift-off. Grounded L remains Kek Wave.':'Reach level 3 and recover one seal to unlock.')+'</p><p>'+RIFT.cost+' SP · '+RIFT.cooldown+'s cooldown · '+RIFT.range+' forward reach</p><p>Launch surviving patrol enemies; stagger guardians. The slam commits your position and facing.</p>');card('<h3>KEK DOMAIN · Ultimate</h3><p>'+ (canDomain(state)?'Your oath is complete. F casts the domain.': 'Recover all three seals and complete your oath with Goribbit.')+'</p><p>Seals '+state.seals.length+' / 3 · Oath '+(state.complete?'fulfilled':'unfinished')+'</p><p>'+DOMAIN.cost+' SP · '+DOMAIN.cooldown+'s cooldown · '+DOMAIN.damage+' damage within '+DOMAIN.radius+' reach</p><p>Plant → Prayer → Pulse → Recover. Protected during the '+DOMAIN.duration+'s cast.</p>');card('<p>Earn one skill point per level. Each further rank requires another level. Your choices change combat immediately.</p>');for(const [id,spec] of Object.entries(SKILLS)){const rank=state.skills[id],preview=skillPreview(state,id),c=card(`<h3>${spec.symbol} ${spec.name} <small>${rank} / ${spec.max}</small></h3><p>${spec.description}</p>${preview.maxed?'<p>Maximum rank reached</p>':'<div class="gear-comparison">'+preview.changes.map(change=>`<p>${({attack:'Sword bonus',warpRange:'Warp reach',warpCost:'Warp SP cost',warpCooldown:'Warp cooldown (seconds)',wave:'Wave bonus',health:'Maximum HP',spirit:'Maximum spirit',regen:'Spirit / second',releaseDuration:'Release duration (seconds)',releaseAttack:'Awakened cut bonus'})[change.key]} ${Number(change.before.toFixed(2))} → ${Number(change.after.toFixed(2))}</p>`).join('')+'</div><p>'+(preview.reasons.length?preview.reasons.join(' · '):'Ready · costs 1 skill point')+'</p>'}`);c.append(button(preview.maxed?'Fully learned':'Learn '+spec.name,()=>learn(state,id),preview.maxed||preview.reasons.length>0));}}
 else if(tab==='Inventory'){for(const [id,item] of Object.entries(ITEMS)){const count=state.inventory[id]||0;if(!count)continue;const c=card(`${icon(id)}<h3>${item.name}${item.slot==='weapon'?' +'+state.gearLevels[id]:''} ${count>1?'×'+count:''}</h3><p>${item.description}</p>${comparison(id)}`);c.append(button(item.slot==='consumable'?'Use '+item.name:state.equipped[item.slot]===id?'Equipped':'Equip '+item.name,()=>item.slot==='consumable'?useItem(state,id):equip(state,id),state.equipped[item.slot]===id));}}
 else {card(`<h3>Your spirit</h3><p>Maximum HP ${st.health} · Spirit ${st.spirit}<br>Sword bonus +${st.attack} · Defense ${st.defense}<br>Warp reach ${st.warpRange} · Cost ${st.warpCost} SP<br>Spirit regeneration ${st.regen} / second</p>`);for(const [slot,id] of Object.entries(state.equipped))card(`${icon(id)}<small>${slot.toUpperCase()}</small><h3>${ITEMS[id].name}${slot==='weapon'?' +'+state.gearLevels[id]:''}</h3><p>${ITEMS[id].description}</p>`);const rank=state.gearLevels[state.equipped.weapon],cost=(rank+1)*20,c=card(`<h3>Goribbit’s forge</h3><p>Stand beside Goribbit to temper your equipped blade or buy supplies. Each temper adds 4 sword damage. Maximum +3.</p><p>${atMentor(state)?'The forge is ready.':'Return to Goribbit at Kek Academy.'}</p>`);c.append(button(rank>=3?'Fully tempered':`Temper blade · ${cost} fragments`,()=>upgradeGear(state),!atMentor(state)||rank>=3||state.fragments<cost));for(const id of ['healthFlask','spiritFlask'])c.append(button(`Buy ${ITEMS[id].name} · 8 fragments`,()=>buyItem(state,id),!atMentor(state)||state.fragments<8));}
 }
 return {open(name){if(name)tab=name;panel.hidden=false;render();},close(){panel.hidden=true;},render};
}
