import {guardFrames,guardCounterPose,drawGuardImpact} from './sword-guard.js';
import {GUARD_ANCHORS} from './guard-layout.js';
import {drawTempleTell,drawTempleImpact,templeCue,templeTelegraph} from './temple-combat.js';
import {templeVisual} from './temple-walk.js';
import {TEMPLE_WALK_ANCHORS} from './temple-walk-layout.js';
import {DISCIPLE_ANCHORS} from './disciple-layout.js';
import {drawKekWave,drawWaveImpact,drawWaveLaunch,waveFrames} from './kek-wave.js';
import {realmPortals} from './portal-state.js';
import {EXTRA_ART,sceneArt,sceneSurface,portalCell,PORTAL_ART,riftCamera} from './realm-art.js';
import {riftFrame,riftFrames,riftPose} from './rift-motion.js';
import {drawRift,drawRiftSlash} from './kek-rift.js';
import {eliteSpec} from './realm-enemies.js';
import {enemyLabelLayout} from './enemy-labels.js';
import {attackTrail} from './attack-motion.js';
import {WorldWeather} from './world-weather.js';
import {DOMAIN_FEET} from './domain-feet.js';
import {domainVisual,domainFragment,domainPose,domainImpact,domainFrames} from './domain-motion.js';
import {stats} from './systems.js';
import {enemyPose,GUARDIAN_STYLE,GUARDIAN_ART,guardianFrames} from './enemy-motion.js';
import {ANCHORS} from './art-layout.js';
import {GROUND, WIDTH, WORLDS} from './core.js';
export const CLIPS = Object.freeze({guard:{row:0,frames:4,fps:10,sheet:'crown-guard-v1'},riftPlant:{row:0,frames:2,fps:10,sheet:'crown-rift-planted-v1'},warp:{row:0,frames:4,fps:12,sheet:'crown-warp'},idle:{row:0,frames:6,fps:7},run:{row:0,frames:8,fps:12,sheet:'crown-run'},attack:{row:2,frames:6,fps:12.5},jump:{row:3,frames:4,fps:8},hurt:{row:3,frames:1,offset:4,fps:1},release:{row:3,frames:1,offset:5,fps:1}});
export function clipFrame(clip,index){const c=CLIPS[clip];return clip==='guard'?{row:Math.floor(index/2),col:index%2,sheet:'crown-guard-v1',cols:2,rows:2,size:350}:clip==='riftPlant'?{row:0,col:index,sheet:'crown-rift-planted-v1',cols:2,rows:1,size:430}:clip==='warp'?{row:Math.floor(index/2),col:index%2,sheet:'crown-warp',cols:2,rows:2,size:250}:clip==='attack'?{row:Math.floor(index/3),col:index%3,sheet:'crown-attack',cols:3,rows:2,size:430}:clip==='run'?{row:Math.floor(index/4),col:index%4,sheet:'crown-run',cols:4,rows:2,size:230}:{row:c.row,col:index+(c.offset||0),sheet:'crown-atlas',cols:6,rows:4,size:230};}
export async function loadArt(){
  const art={};await Promise.all(['crown-domain-rise-v1','crown-domain-between-v1','crown-domain-official-v1','kek-domain-spirit-v1',...Object.values(GUARDIAN_ART),'crown-warp','item-atlas','crown-atlas','crown-run','crown-attack','enemy-atlas','approach2-enemies-v1','mentor','effigy',...WORLDS.map(w=>w.art),...EXTRA_ART].map(async key=>{const im=new Image();im.src=`assets/${key}.${WORLDS.some(w=>w.art===key)||key.includes('-approach')?'webp':'png'}`;await im.decode();art[key]=im;}));return art;
}
export function drawSprite(ctx,im,row,col,cols,rows,x,y,size,face=1,alpha=1){
  const cw=im.width/cols,ch=im.height/rows;const key=Object.keys(ANCHORS).find(k=>im.src?.includes(k+'.')||im.assetKey===k);const guardian=[...Object.values(GUARDIAN_ART),'crown-domain-official-v1','crown-domain-between-v1','crown-domain-rise-v1','jade-disciple-v1'].some(k=>im.src?.includes(k+'.')||im.assetKey===k);const elite=im.src?.includes('approach2-enemies-v1.')||im.assetKey==='approach2-enemies-v1';const planted=im.src?.includes('crown-rift-planted-v1.')||im.assetKey==='crown-rift-planted-v1';const disciple=im.src?.includes('jade-disciple-v1.')||im.assetKey==='jade-disciple-v1';const walk=Object.keys(TEMPLE_WALK_ANCHORS).find(k=>im.src?.includes(k+'.')||im.assetKey===k);const guard=im.src?.includes('crown-guard-v1.')||im.assetKey==='crown-guard-v1';const a=guard?GUARD_ANCHORS[row*cols+col]:walk?TEMPLE_WALK_ANCHORS[walk][row*cols+col]:disciple?DISCIPLE_ANCHORS[row*cols+col]:planted?{x:col===0?.50:.47,y:500/512}:guardian||elite?{x:.5,y:504/512}:ANCHORS[key]?.[row*cols+col]||{x:.5,y:1};ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(face,1);ctx.drawImage(im,col*cw,row*ch,cw,ch,-a.x*size,-a.y*size,size,size);ctx.restore();
}
export function heroFrame(p,time){
  if(p.rift){const f=riftFrame(p.rift.elapsed);return clipFrame(f.clip,f.index);}
  if(p.domain)return domainFrame(domainFrames(p.domain.elapsed).index);
  if(p.warp)return clipFrame('warp',p.warp.elapsed<.06?0:p.warp.elapsed<.2?1:p.warp.elapsed<.29?2:3);
  if(p.hurt>0)return clipFrame('hurt',0);
  const guard=guardFrames(p);if(guard)return guard.to===null?clipFrame('idle',0):clipFrame('guard',guard.to);
  const wave=waveFrames(p);if(wave&&p.y>=GROUND)return wave.current===null?clipFrame('idle',0):clipFrame('attack',wave.current);
  if(p.attack>0)return clipFrame('attack',Math.min(5,Math.floor(p.anim*12.5)));
  if(p.y<GROUND-1)return clipFrame('jump',p.vy<-100?1:p.vy<100?2:3);
  if(p.release>0 && p.mode==='idle')return clipFrame('release',0);
  return p.mode==='run'||p.dash>0?clipFrame('run',Math.floor(time*12)%8):clipFrame('idle',Math.floor(time*7)%6);
}
function domainFrame(index){return index<0?clipFrame('idle',0):index===6?{row:0,col:0,sheet:'crown-domain-rise-v1',cols:1,rows:1,size:300}:index>=4?{row:0,col:index-4,sheet:'crown-domain-between-v1',cols:2,rows:1,size:300}:{row:Math.floor(index/2),col:index%2,sheet:'crown-domain-official-v1',cols:2,rows:2,size:index===0||index===3?270:300};}
function label(ctx,text,x,y,color='#ccd9d5',size=12){ctx.save();ctx.font=`${size}px Georgia`;ctx.textAlign='center';ctx.fillStyle='#071017';ctx.fillText(text,x+1,y+1);ctx.fillStyle=color;ctx.fillText(text,x,y);ctx.restore();}
function glow(ctx,x,y,r,color,alpha=1){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore();}
export class Renderer {
  constructor(canvas,art){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.art=art;this.camera=0;this.fx=[];this.echoes=[];this.shake=0;this.freeze=0;this.reduced=false;this.lastEcho=0;this.worldFade=0;this.weather=new WorldWeather();}
  blendPoses(ctx,from,to,x,y,face,blend){
    // Add weighted poses on transparent pixels before compositing onto the world.
    // Drawing them directly over the scenery dims shared opaque pixels mid-blend.
    if(!this.poseLayer){this.poseLayer=this.canvas.ownerDocument?this.canvas.ownerDocument.createElement('canvas'):new this.canvas.constructor(640,640);this.poseLayer.width=640;this.poseLayer.height=640;}
    const layer=this.poseLayer.getContext('2d');layer.clearRect(0,0,640,640);layer.save();
    drawSprite(layer,this.art[from.sheet],from.row,from.col,from.cols,from.rows,320,624,from.size,face,1-blend);
    layer.globalCompositeOperation='lighter';drawSprite(layer,this.art[to.sheet],to.row,to.col,to.cols,to.rows,320,624,to.size,face,blend);
    layer.restore();ctx.drawImage(this.poseLayer,x-320,y-624);
  }
  effect(event,state){const p=state.player;this.weather.react(event,state,this.reduced);
    if(event.type==='templeLotus'||event.type==='templeCleave'){this.fx.push({...event,life:.35,max:.35});this.burst(event.x,event.y-20,8,'#efd47e',100);}
    if(event.type==='wave'){this.burst(event.x,event.y,14,'#9cffd6',150);this.fx.push({type:'waveLaunch',x:event.x,y:event.y,face:event.face,life:.18,max:.18,color:'#9cffd6'});}if(event.type==='waveHit'){this.burst(event.x,event.y,18,'#6bffc0',230);this.fx.push({type:'waveImpact',x:event.x,y:event.y,face:event.face,color:'#caffea',life:.24,max:.24});}
    if(event.type==='riftImpact'){this.freeze=.045;this.shake=this.reduced?0:3;this.burst(event.x,GROUND-8,24,'#81ffc1',220);this.fx.push({type:'riftRing',x:event.x,y:GROUND-5,life:.25,max:.25,color:'#8cffc5'});}if(event.type==='riftHit')this.burst(event.x,event.y-65,10,'#9dffcc',130);
    if(event.type==='hit'){this.freeze=.045;this.fx.push({type:'number',x:event.x,y:event.y-35,text:event.amount,color:'#fff0c7',life:.65,max:.65});this.burst(event.x,event.y,15,'#ebdba6',240);}
    if(event.type==='guardBlock'||event.type==='guardBreak'){this.freeze=this.reduced?0:.045;this.shake=this.reduced?0:2;this.fx.push({...event,life:.24,max:.24});this.burst(event.x,event.y,event.type==='guardBreak'?16:10,event.type==='guardBreak'?'#ffc08b':'#b6ffda',135);}
    if(event.type==='hurt'){this.shake=0;this.burst(event.x,event.y,16,'#ec938f',200);}
    if(event.type==='defeat')this.burst(event.x,event.y,event.boss?40:23,state.world==='frozen'?'#a4e6f6':'#b798e6',150);
    if(event.type==='land')this.burst(event.x,GROUND-3,9,'#a0b2b3',80);
    if(event.type==='warp'){this.echoes.push({x:event.from,y:event.y,face:event.face,...clipFrame('warp',0),life:.32,origin:true});this.burst(event.from,event.y-70,10,'#91f4c1',100);}
    if(event.type==='warpLand'){this.burst(event.x,GROUND-5,12,'#aaf3d1',120);this.fx.push({type:'ring',x:event.x,y:GROUND-5,life:.22,max:.22,color:'#aaf3d1'});}
    if(event.type==='dash')this.burst(p.x,p.y-50,16,'#b6dfd8',160);
    if(event.type==='release'||event.type==='seal'||event.type==='level'){this.burst(p.x,p.y-90,50,'#d4d6ff',290);this.fx.push({type:'ring',x:p.x,y:p.y-90,life:.8,max:.8,color:'#ccd8ff'});}
    if(event.type==='enemySwing')this.fx.push({type:'cut',x:event.x+event.face*65,y:event.y,face:event.face,color:'#ff9f9b',life:.18,max:.18});
    if(event.type==='domainPulse'){this.burst(event.x,GROUND-20,35,'#8effbb',260);}if(event.type==='enemyWave')this.burst(event.x,event.y,18,GUARDIAN_STYLE[event.world].color,160);
    if(event.type==='world'){this.worldFade=1;this.camera=0;this.fx=[];this.echoes=[];}
  }
  burst(x,y,count,color,speed){if(this.reduced)count=Math.ceil(count/4);for(let i=0;i<count;i++){const a=i*2.399963,v=speed*(.3+(i%7)/10);this.fx.push({type:'spark',x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-25,life:.25+(i%5)*.08,max:.6,color});}}
  update(dt,s){this.weather.update(dt,s,this.reduced);if(s.player.attack<=0&&s.player.hurt<=0){const x=s.player.x-this.camera,lo=this.canvas.width*.32,hi=this.canvas.width*.65;const target=x<lo?s.player.x-lo:x>hi?s.player.x-hi:this.camera;this.camera+=(Math.max(0,Math.min(WIDTH-this.canvas.width,target))-this.camera)*(s.player.warp?1:Math.min(1,dt*8));}this.shake=Math.max(0,this.shake-dt*25);this.freeze=Math.max(0,this.freeze-dt);this.worldFade=Math.max(0,this.worldFade-dt*1.8);this.fx=this.fx.filter(f=>{f.life-=dt;if(f.type==='spark'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=dt*220;}if(f.type==='number')f.y-=dt*40;return f.life>0;});this.echoes=this.echoes.filter(e=>(e.life-=dt)>0);if(s.player.warp?.elapsed>.06 && s.player.warp.elapsed<.2 && s.time-this.lastEcho>.08 && !this.reduced){this.lastEcho=s.time;this.echoes.push({x:s.player.x,y:s.player.y,face:s.player.face,...heroFrame(s.player,s.time),life:.12});}}
  draw(s,{emptyMap=false,showcase=false}={}){const ctx=this.ctx,t=s.time,w=WORLDS.find(w=>w.id===s.world),p=s.player;const sw=this.canvas.width,sh=this.canvas.height;this.floorOffset=sh*.82-GROUND;ctx.clearRect(0,0,sw,sh);ctx.save();this.world=s.world;const riftView=riftCamera(p.rift?.elapsed,this.reduced);if(riftView.zoom>1){const px=p.x-this.camera,py=sh*.82;ctx.translate(px,py);ctx.scale(riftView.zoom,riftView.zoom);ctx.translate(-px,-py);}const impact=p.domain?domainImpact(p.domain.elapsed,this.reduced):null;if(impact){const pivotX=p.x-this.camera,pivotY=sh*.82;ctx.translate(pivotX,pivotY);ctx.scale(impact.zoom,impact.zoom);ctx.translate(-pivotX,-pivotY);}if(this.shake && !this.reduced)ctx.translate(Math.sin(t*141)*this.shake,Math.cos(t*113)*this.shake*.5);
    // Background is wider than the viewport. Gentle parallax preserves the painted floor.
    const scene=sceneArt(s.world,s.zone),im=this.art[scene]||this.art[w.art],bh=scene!==w.art?Math.max(sh*.82/sceneSurface(s.world,s.zone),sw/(im.width/im.height)):Math.max(sh*(s.zone==='arena'&&s.world!=='temple'?1.48:1.24),sw/1.5),bw=bh*im.width/im.height+sw*.32;const offset=this.camera*(s.zone==='arena'?.22:s.zone==='approach2'?.18:.12);const surface=sceneSurface(s.world,s.zone);ctx.drawImage(im,-offset,sh*.82-bh*surface,bw,bh);
    const shade=ctx.createLinearGradient(0,0,0,720);shade.addColorStop(0,'#08122128');shade.addColorStop(.7,'#06101600');shade.addColorStop(1,'#05101aba');ctx.fillStyle=shade;ctx.fillRect(0,0,sw,sh);
    if(riftView.shade){ctx.fillStyle=`rgba(0,8,12,${riftView.shade})`;ctx.fillRect(0,0,sw,sh);}this.weather.draw(ctx,s,this.camera,sh*.82,sw,false,this.reduced);ctx.save();ctx.translate(-this.camera,this.floorOffset);
    // A low-opacity world floor makes collision height legible without hiding the artwork.
    ctx.fillStyle='#0b161920';ctx.fillRect(0,GROUND,WIDTH,130);ctx.strokeStyle=w.color+'35';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,GROUND+2);ctx.lineTo(WIDTH,GROUND+2);ctx.stroke();
    if(p.domain){const elapsed=p.domain.elapsed,rise=Math.min(1,Math.max(0,(elapsed-.25)/.6)),fade=Math.min(1,(2.4-elapsed)/.65),opacity=rise*fade;ctx.save();ctx.fillStyle='#021009';ctx.globalAlpha=this.reduced?.1:.2;ctx.fillRect(this.camera,-this.floorOffset,sw,sh);ctx.restore();const spirit=this.art['kek-domain-spirit-v1'];if(spirit){ctx.save();ctx.globalAlpha=opacity*(this.reduced?.35:.58);const height=Math.min(sh*.76,520),width=height*spirit.width/spirit.height;const visual=domainVisual(elapsed,this.reduced);if(visual.fragmented){ctx.drawImage(spirit,p.x-width/2,GROUND-height,width,height);for(let row=0;row<8;row++)for(let col=0;col<6;col++){const f=domainFragment(col,row,visual.dissolve);ctx.save();ctx.globalAlpha=visual.opacity*.8;ctx.fillStyle='#b1ffcc';ctx.translate(p.x-width/2+(col+.5)*width/6+f.x,GROUND-height+(row+.5)*height/8+f.y);ctx.rotate(col*.7+row);const radius=3+(row+col)%4;ctx.beginPath();ctx.moveTo(0,-radius*2);ctx.lineTo(radius,0);ctx.lineTo(0,radius*2);ctx.lineTo(-radius,0);ctx.closePath();ctx.fill();ctx.restore();}}else ctx.drawImage(spirit,p.x-width/2,GROUND-height,width,height);ctx.restore();}ctx.save();ctx.strokeStyle='#88ffc0';ctx.globalAlpha=Math.max(.15,opacity)*.8;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(p.x,GROUND+3,420*rise,20,0,0,Math.PI*2);ctx.stroke();if(!this.reduced){for(let i=0;i<12;i++){const x=p.x+Math.sin(i*2.4)*370*rise;ctx.globalAlpha=opacity*.35;ctx.beginPath();ctx.moveTo(x,GROUND);ctx.lineTo(x,GROUND-60-(i%4)*25);ctx.stroke();}}if(impact?.alpha>0){ctx.globalAlpha=impact.alpha;ctx.strokeStyle='#d0ffe1';ctx.lineWidth=4*(1-impact.ripple)+1;ctx.beginPath();ctx.ellipse(p.x,GROUND+3,50+370*impact.ripple,5+16*impact.ripple,0,0,Math.PI*2);ctx.stroke();}ctx.restore();if(!showcase)label(ctx,'KEK DOMAIN',p.x,GROUND-Math.min(sh*.76,520)-15,'#b8ffdb',15);}
    for(let i=0;i<0;i++){const x=((i*173+t*(s.world==='frozen'?13:5))%WIDTH),y=(i*83+t*(s.world==='frozen'?19:-7))%680;ctx.globalAlpha=.14+Math.sin(t+i)*.09;ctx.fillStyle=w.color;ctx.beginPath();ctx.arc(x,y,s.world==='frozen'?1.8:1.1,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
    if(!emptyMap){if(s.world==='academy'){this.mentor(ctx,t);this.dummy(ctx,s,t);label(ctx,'TRAINING COURT',870,GROUND+45,'#adbbab',11);label(ctx,'Practice three cuts · J',870,GROUND+65,'#809d9e',10);}
    else {if(s.zone==='arena'){if(!showcase)label(ctx,s.world==='temple'?'INNER SANCTUARY':w.boss.toUpperCase()+' · GUARDIAN ARENA',1700,GROUND-(s.world==='temple'?395:330),w.color,16);}else if(!showcase){glow(ctx,1360,GROUND-90,80,w.color,.3);drawSprite(ctx,this.art['item-atlas'],2,1,4,3,1360,GROUND-35,95);label(ctx,s.discoveries.includes(s.world)?'ECHO ATTUNED':'E · ATTUNE SHRINE',1360,GROUND-145,w.color,11);}for(const e of s.enemies)this.enemy(ctx,e,t,w);const labels=enemyLabelLayout(s.enemies,GROUND);for(const e of s.enemies)if(!e.dead&&!showcase)this.enemyReadout(ctx,e,w,labels.get(e.id));}}
    if(!emptyMap&&!showcase)for(const portal of realmPortals(s))this.gate(ctx,portal.x,t,portal.locked?'#78838a':w.color,portal.title,portal.prompt);
    for(const r of s.rifts||[])drawRift(ctx,r,GROUND,this.reduced,this.art['kek-rift-eruptions-v1']);
    for(const d of s.drops){if(d.kind==='loot'){glow(ctx,d.x,d.y,35,w.color,.3);if(d.item){const i={frostFang:1,emberFang:2,voidFang:3,healthFlask:10}[d.item];drawSprite(ctx,this.art['item-atlas'],Math.floor(i/4),i%4,4,3,d.x,d.y,55);}else{ctx.fillStyle='#9ce3c0';ctx.fillRect(d.x-5,d.y-10,10,10);}continue;}glow(ctx,d.x,d.y,80,w.color,.65);ctx.save();ctx.translate(d.x,d.y+Math.sin(t*3)*8);ctx.rotate(t*.5);ctx.strokeStyle='#f4e5ba';ctx.lineWidth=3;ctx.strokeRect(-17,-17,34,34);ctx.rotate(-t);ctx.strokeRect(-10,-10,20,20);ctx.restore();label(ctx,'RECOVER THE SEAL',d.x,d.y-50,'#ffe9a9',12);}
    for(const e of this.echoes){ctx.save();ctx.shadowColor='#67f5b0';ctx.shadowBlur=e.origin?18:5;ctx.filter='sepia(1) saturate(2) hue-rotate(85deg)';drawSprite(ctx,this.art[e.sheet],e.row,e.col,e.cols,e.rows,e.x,e.y,e.size,e.face,e.origin?e.life*1.9:e.life*.8);ctx.restore();}if(p.warp&&p.warp.elapsed>.06&&p.warp.elapsed<.2){ctx.strokeStyle='#92ffd4';ctx.lineWidth=2;ctx.globalAlpha=.4;ctx.beginPath();ctx.moveTo(p.warp.from,p.y-65);ctx.lineTo(p.x,p.y-65);ctx.stroke();ctx.globalAlpha=1;}
    const grounded= Math.max(.25,1-(GROUND-p.y)/350);ctx.save();ctx.globalAlpha=grounded;ctx.fillStyle='#030b15aa';ctx.beginPath();ctx.ellipse(p.x,GROUND+3,45*grounded,9*grounded,0,0,Math.PI*2);ctx.fill();ctx.restore();
    if(p.release>0)glow(ctx,p.x,p.y-105,140,'#aca5f8',.22+Math.sin(t*8)*.05);
    if(p.domain){const f=heroFrame(p,t),pose=domainPose(p.domain.elapsed,p.face,this.reduced),feet=DOMAIN_FEET[f.sheet]?.[f.row*f.cols+f.col];if(feet){ctx.save();ctx.fillStyle='#020809';ctx.globalAlpha=.42;for(const foot of feet){ctx.beginPath();ctx.ellipse(p.x+foot.x*f.size*p.face*pose.scaleX,GROUND+1,foot.width*f.size*pose.scaleX*.52,3,0,0,Math.PI*2);ctx.fill();}ctx.restore();}}
    drawRiftSlash(ctx,p,this.reduced);const frame=heroFrame(p,t);if(impact?.echo>0){ctx.save();ctx.filter='sepia(1) saturate(3) hue-rotate(85deg)';const size=frame.size*(1+(impact.zoom-1)*3);drawSprite(ctx,this.art[frame.sheet],frame.row,frame.col,frame.cols,frame.rows,p.x,p.y,size,p.face,impact.echo);ctx.restore();}ctx.save();if(!emptyMap&&s.world!=='academy'&&s.enemies.some(e=>!e.dead&&Math.abs(e.x-p.x)<(e.boss?160:100)&&Math.abs(e.y-p.y)<230)){ctx.shadowColor='#c0ffe1';ctx.shadowBlur=this.reduced?3:7;}if(p.rift){const pose=riftPose(p.rift.elapsed,p.face,this.reduced);ctx.translate(p.x,p.y);ctx.transform(pose.scaleX,0,pose.lean,pose.scaleY,0,0);ctx.translate(-p.x,-p.y);}if(p.domain){const pose=domainPose(p.domain.elapsed,p.face,this.reduced);ctx.translate(p.x,p.y);ctx.transform(pose.scaleX,0,pose.lean,pose.scaleY,0,0);ctx.translate(-p.x,-p.y);}if(p.rift){const f=riftFrames(p.rift.elapsed,this.reduced),previous=clipFrame(f.previous.clip,f.previous.index);if(f.blend<1)this.blendPoses(ctx,previous,frame,p.x,p.y,p.face,f.blend);else drawSprite(ctx,this.art[frame.sheet],frame.row,frame.col,frame.cols,frame.rows,p.x,p.y,frame.size,p.face);}else if(p.domain){const f=domainFrames(p.domain.elapsed,this.reduced),previous=domainFrame(f.previous);if(f.blend<1)this.blendPoses(ctx,previous,frame,p.x,p.y,p.face,f.blend);else drawSprite(ctx,this.art[frame.sheet],frame.row,frame.col,frame.cols,frame.rows,p.x,p.y,frame.size,p.face);}else if(guardFrames(p,this.reduced)){const f=guardFrames(p,this.reduced),from=f.from===null?clipFrame('idle',0):clipFrame('guard',f.from),to=f.to===null?clipFrame('idle',0):clipFrame('guard',f.to);if(f.blend>0&&f.blend<1)this.blendPoses(ctx,from,to,p.x,p.y,p.face,f.blend);else{const selected=f.blend===0?from:to;drawSprite(ctx,this.art[selected.sheet],selected.row,selected.col,selected.cols,selected.rows,p.x,p.y,selected.size,p.face);}}else if(guardCounterPose(p,this.reduced)){const f=guardCounterPose(p,this.reduced);this.blendPoses(ctx,clipFrame('guard',f.from),frame,p.x,p.y,p.face,f.blend);}else if(waveFrames(p,this.reduced)&&p.y>=GROUND){const wave=waveFrames(p,this.reduced),previous=wave.previous===null?clipFrame('idle',0):clipFrame('attack',wave.previous);this.blendPoses(ctx,previous,frame,p.x,p.y,p.face,wave.blend);}else drawSprite(ctx,this.art[frame.sheet],frame.row,frame.col,frame.cols,frame.rows,p.x,p.y,frame.size,p.face,p.warp&&p.warp.elapsed>.06&&p.warp.elapsed<.2?.18:1);ctx.restore();
    const trail=attackTrail(p);if(trail){ctx.save();ctx.translate(p.x,p.y-95);ctx.scale(p.face,1);ctx.strokeStyle=p.release>0?'#dcceff':stats(s).color;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=this.reduced?0:18;ctx.lineWidth=trail.width;ctx.beginPath();ctx.ellipse(40,0,trail.reach,trail.height,trail.rotation,trail.angle-trail.direction*.9,trail.angle,trail.direction<0);ctx.stroke();ctx.lineWidth=1.5;ctx.strokeStyle='#ffffff';ctx.beginPath();ctx.ellipse(40,0,trail.reach+8,trail.height+5,trail.rotation,trail.angle-trail.direction*.7,trail.angle+trail.direction*.1,trail.direction<0);ctx.stroke();ctx.restore();}
    for(const q of s.projectiles){if(q.friendly){drawKekWave(ctx,q,this.reduced);continue;}const color=q.friendly?'#bdf7ec':GUARDIAN_STYLE[q.world]?.color||'#ffb4b9';glow(ctx,q.x,q.y,65,color,.4);ctx.save();ctx.translate(q.x,q.y);ctx.scale(Math.sign(q.vx),1);ctx.strokeStyle=color;ctx.lineWidth=q.friendly?4:6;ctx.shadowBlur=this.reduced?0:16;ctx.shadowColor=color;ctx.beginPath();ctx.moveTo(-35,-38);ctx.quadraticCurveTo(45,0,-35,38);ctx.stroke();if(!this.reduced){for(let i=0;i<3;i++){ctx.globalAlpha=.3-i*.08;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-45-i*15,-25+i*4);ctx.quadraticCurveTo(-12-i*15,0,-45-i*15,25-i*4);ctx.stroke();}}ctx.restore();}
    for(const f of this.fx){ctx.save();ctx.globalAlpha=Math.min(1,f.life/f.max*1.5);ctx.fillStyle=f.color;ctx.strokeStyle=f.color;if(f.type==='guardBlock'||f.type==='guardBreak')drawGuardImpact(ctx,f,this.reduced);if(f.type==='templeLotus'||f.type==='templeCleave')drawTempleImpact(ctx,f,this.reduced);if(f.type==='waveImpact')drawWaveImpact(ctx,f,this.reduced);if(f.type==='waveLaunch')drawWaveLaunch(ctx,f,this.reduced);if(f.type==='spark'){ctx.fillRect(f.x,f.y,3,3);}if(f.type==='number'){ctx.font='bold 22px Georgia';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y);}if(f.type==='ring'){ctx.lineWidth=2;ctx.beginPath();ctx.arc(f.x,f.y,(1-f.life/f.max)*190,0,Math.PI*2);ctx.stroke();}if(f.type==='riftRing'){ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(f.x,f.y,25+(1-f.life/f.max)*140,3+(1-f.life/f.max)*14,0,0,Math.PI*2);ctx.stroke();}if(f.type==='cut'){ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y,75,-1.4,1.4);ctx.stroke();}ctx.restore();}
    // Foreground mist has a separate speed from the painted architecture.
    for(let i=0;i<5;i++){glow(ctx,((t*18+i*680)%3200)-200,GROUND+90,200,w.color,.025);}
    ctx.restore();this.weather.draw(ctx,s,this.camera,sh*.82,sw,true,this.reduced);if(impact?.flash>0){ctx.save();ctx.globalAlpha=impact.flash;ctx.fillStyle='#baffd5';ctx.fillRect(0,0,sw,sh);ctx.restore();}if(riftView.flash){ctx.save();ctx.globalAlpha=riftView.flash;ctx.fillStyle='#d9ffe8';ctx.fillRect(0,0,sw,sh);ctx.restore();}if(this.worldFade>0){ctx.globalAlpha=this.worldFade;ctx.fillStyle='#09131c';ctx.fillRect(0,0,sw,sh);ctx.globalAlpha=1;}
    ctx.restore();
  }
  mentor(ctx,t){const im=this.art.mentor;const size=210,width=size*im.width/im.height;ctx.save();drawSprite(ctx,im,0,0,1,1,490,GROUND,size);ctx.restore();glow(ctx,490,GROUND-170,40,'#ffcd8b',.15);label(ctx,'MASTER GORIBBIT',490,GROUND-230,'#e5d5af',12);label(ctx,'Sword sage · E to speak',490,GROUND-212,'#a6b9b4',10);}
  dummy(ctx,s,t){const x=870,im=this.art.effigy,size=200,width=size*im.width/im.height;ctx.save();ctx.translate(x,GROUND);const flash=s.enemies[0]?.hitFlash||0;ctx.rotate(flash>0?Math.sin(t*60)*.05:0);const a=ANCHORS.effigy[0];ctx.drawImage(im,-a.x*size,-a.y*size,size,size);ctx.restore();if(flash>0)glow(ctx,x,GROUND-95,65,'#efd59b',flash);label(ctx,`${s.training} / 3 CUTS`,x,GROUND-215,'#dbcaa5',12);}
  gate(ctx,x,t,color,text,prompt='E · CROSS THE VEIL'){
    const locked=color==='#78838a',active=locked?.15:1,im=this.art[PORTAL_ART];
    ctx.save();ctx.translate(x,GROUND);ctx.fillStyle='#01070b88';ctx.beginPath();ctx.ellipse(0,3,95,12,0,0,Math.PI*2);ctx.fill();
    glow(ctx,0,-135,130,color,.22*active);const g=ctx.createRadialGradient(0,-135,8,0,-135,105);g.addColorStop(0,locked?'#152028':'#07151ed0');g.addColorStop(.6,color+'55');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.ellipse(0,-135,59,109,0,0,Math.PI*2);ctx.fill();
    ctx.save();ctx.beginPath();ctx.ellipse(0,-135,59,109,0,0,Math.PI*2);ctx.clip();ctx.strokeStyle=color;ctx.globalAlpha=active*.55;ctx.lineWidth=2;for(let i=0;i<(locked?0:this.reduced?3:7);i++){ctx.beginPath();const y=-240+((t*26+i*37)%215);ctx.ellipse(Math.sin(t+i)*12,y,48,12+i*2,t*.15+i,0,Math.PI*2);ctx.stroke();}ctx.restore();
    if(im){const cell=portalCell(this.world),cw=im.width/4,height=300,width=height*cw/im.height;ctx.save();if(locked)ctx.filter='grayscale(.9) brightness(.65)';ctx.drawImage(im,cell*cw,0,cw,im.height,-width/2,-height,width,height);ctx.restore();}
    if(!this.reduced&&!locked){ctx.fillStyle=color;for(let i=0;i<12;i++){const phase=t*.4+i*2.399;ctx.globalAlpha=.25+(.5+.5*Math.sin(phase))*.5;ctx.beginPath();ctx.arc(Math.cos(phase)*75,-135+Math.sin(phase)*120,1.5,0,Math.PI*2);ctx.fill();}}ctx.restore();
    label(ctx,text,x,GROUND-315,color,12);label(ctx,prompt,x,GROUND+28,'#b4c5c7',10);
  }
  enemyReadout(ctx,e,w,box){
    if(!box)return;const {x,y}=box,style=GUARDIAN_STYLE[e.world];
    if(x!==e.x){ctx.save();ctx.strokeStyle='#a8c9d655';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y+29);ctx.lineTo(e.x,GROUND-(e.boss?245:185));ctx.stroke();ctx.restore();}
    label(ctx,e.boss?w.boss:eliteSpec(e)?.name||w.enemy,x,y,e.boss?'#efd2a5':'#c0ccda',e.boss?15:11);
    const cue=e.world==='temple'?templeCue(e):e.mode==='windup'?(e.boss?(e.attackCount%2===1?style.wave:style.name):eliteSpec(e)?.cue||'INCOMING CUT'):e.mode==='recover'?'OPEN':'';
    if(cue)label(ctx,cue,x,y+15,e.mode==='windup'?'#ffbd92':'#a6efd3',10);
    ctx.fillStyle='#122029';ctx.fillRect(x-38,y+23,76,4);ctx.fillStyle=e.boss?'#e9b38f':w.color;ctx.fillRect(x-38,y+23,76*e.hp/e.maxHp,4);
    const tell=e.world==='temple'?templeTelegraph(e):null;if(tell){ctx.fillStyle='#18262b';ctx.fillRect(x-38,y+31,76,3);ctx.fillStyle=tell.phase==='recover'?'#87efc1':tell.urgent?'#fff0b5':'#d3a461';ctx.fillRect(x-38,y+31,76*tell.progress,3);}
  }
  enemy(ctx,e,t,w){if(e.dead && e.death<=0)return;const row=['frozen','crimson','void'].indexOf(e.world);const pose=enemyPose(e,t,this.reduced),col=pose.col;const size=e.boss?687:512;const alpha=e.dead?e.death/.7:1;const style=GUARDIAN_STYLE[e.world];
    if(e.mode==='windup'&&e.elite==='caster'&&e.world==='frozen'){ctx.strokeStyle=w.color;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(e.targetX,GROUND+3,75,12,0,0,Math.PI*2);ctx.stroke();label(ctx,'FROST ERUPTION',e.targetX,GROUND-45,w.color,10);}if(e.world==='temple')drawTempleTell(ctx,e,GROUND,this.reduced);if(e.mode==='windup'&&e.world!=='temple'){const reach=e.elite==='melee'?eliteSpec(e).range+(e.world==='crimson'?0:65):0,warnX=reach?e.x+e.face*reach/2:e.x+e.face*55,warnRadius=reach?reach/2+15:e.boss?135:90;glow(ctx,e.x,GROUND-95,100,'#fb807a',.28);ctx.strokeStyle='#ef8a78';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(warnX,GROUND+3,warnRadius,10,0,0,Math.PI*2);ctx.stroke();const windup=1-Math.max(0,e.timer)/(e.boss?.65:e.elite?.9:.55);ctx.strokeStyle='#ffe0a2';ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(warnX,GROUND+3,warnRadius,10,0,-Math.PI/2,-Math.PI/2+Math.PI*2*windup);ctx.stroke();}

    ctx.fillStyle='#060f1b99';ctx.beginPath();ctx.ellipse(e.x,GROUND+3,e.boss?57:38,8,0,0,Math.PI*2);ctx.fill();
    ctx.save();ctx.translate(e.x,e.y);ctx.transform(pose.scaleX,0,pose.lean,pose.scaleY,0,0);const guardian=this.art[GUARDIAN_ART[e.world]];
    if(e.world==='temple'){
      const f=templeVisual(e,this.reduced);ctx.globalAlpha=alpha;
      if(f.blend>0&&f.blend<1)this.blendPoses(ctx,f.from,f.to,0,0,-e.face,f.blend);
      else {const frame=f.blend===0?f.from:f.to;drawSprite(ctx,this.art[frame.sheet],frame.row,frame.col,frame.cols,frame.rows,0,0,frame.size,-e.face,alpha);}
    }else if(e.boss&&guardian){const f=guardianFrames(e,t,this.reduced);if(f.blend<1)drawSprite(ctx,guardian,1,1,2,2,0,0,600,e.face,alpha*(1-f.blend));drawSprite(ctx,guardian,Math.floor(f.index/2),f.index%2,2,2,0,0,600,e.face,alpha*f.blend);}else if(e.elite)drawSprite(ctx,this.art['approach2-enemies-v1'],eliteSpec(e).row,col,4,6,0,0,512,e.face,alpha);else drawSprite(ctx,this.art['enemy-atlas'],row,col,4,3,0,0,size,col===3?e.face:-e.face,alpha);ctx.restore();
    if(e.boss&&!e.dead){
      ctx.save();ctx.translate(e.x,GROUND-245);ctx.strokeStyle=style.color;ctx.fillStyle=style.color;ctx.globalAlpha=e.mode==='windup'?.55+pose.charge*.4:.42;ctx.lineWidth=2;
      // Each guardian carries a realm sigil; its pulse charges with the strike.
      for(let i=0;i<5;i++){const a=-Math.PI/2+(i-2)*.34,x=Math.cos(a)*48,y=Math.sin(a)*48;ctx.beginPath();if(style.shape==='crystal'){ctx.moveTo(x,y-12);ctx.lineTo(x+5,y);ctx.lineTo(x,y+8);ctx.lineTo(x-5,y);ctx.closePath();}else if(style.shape==='flame'){ctx.moveTo(x,y-12);ctx.quadraticCurveTo(x+13,y+4,x,y+8);ctx.quadraticCurveTo(x-8,y,x,y-12);}else ctx.arc(x,y,4,0,Math.PI*2);ctx.stroke();}ctx.restore();

      if(e.mode==='strike'&&e.world!=='temple'){ctx.save();ctx.translate(e.x,GROUND-105);ctx.scale(e.face,1);ctx.strokeStyle=style.color;ctx.lineWidth=6;ctx.globalAlpha=.8;ctx.beginPath();ctx.ellipse(55,0,145,85,0,-1.4,1.1);ctx.stroke();ctx.restore();}
    }
    if(e.hitFlash>0){ctx.globalAlpha=e.hitFlash*2;glow(ctx,e.x,GROUND-100,65,'#ffffff',.5);ctx.globalAlpha=1;}

  }
}
