import {enterArena} from '../core.js';
import test from 'node:test';import assert from 'node:assert/strict';import {createState,act,step,snapshot,enterWorld,DOMAIN,domainReady} from '../core.js';
const unlocked=()=>createState({version:1,xp:600,oath:true,training:3,seals:['frozen','crimson','void'],complete:true});
test('domain requires completed oath, grounded cast and sufficient spirit',()=>{const s=createState();assert.equal(act(s,'domain'),false);const u=unlocked();u.player.sp=79;assert.equal(act(u,'domain'),false);u.player.sp=100;u.player.y=580;assert.equal(act(u,'domain'),false);u.player.y=590;assert.equal(act(u,'domain'),true);assert.equal(u.player.sp,20);assert.equal(act(u,'domain'),false);});
test('domain roots Crown and pulses once inside its range',()=>{const s=unlocked();s.world='frozen';s.player.x=1000;s.enemies=[{id:1,x:1100,y:590,hp:210,maxHp:210,world:'frozen',boss:true,face:-1,mode:'idle',timer:100,stun:0,anim:0,hitFlash:0,attackCount:0,dead:false},{id:2,x:1700,y:590,hp:210,maxHp:210,world:'frozen',boss:true,face:-1,mode:'idle',timer:100,stun:0,anim:0,hitFlash:0,attackCount:0,dead:false}];act(s,'domain');for(let i=0;i<140;i++)step(s,{right:true},1/60);assert.equal(s.player.x,1000);assert.equal(s.enemies[0].hp,110);assert.equal(s.enemies[1].hp,210);assert.equal(s.events.filter(e=>e.type==='domainPulse').length,1);assert.equal(act(s,'dash'),false);});
test('domain cooldown persists reload and realm travel cancels cast',()=>{const s=unlocked();act(s,'domain');const loaded=createState(snapshot(s));assert.equal(loaded.player.domainCooldown,DOMAIN.cooldown);assert.equal(loaded.player.domain,null);enterWorld(s,'academy');assert.equal(s.player.domain,null);assert.equal(s.player.domainCooldown,30);});
test('domain result counts only living enemies inside its radius',()=>{const s=unlocked();s.player.x=2250;assert.equal(enterWorld(s,'frozen'),true);s.player.x=800;act(s,'domain');for(let i=0;i<80;i++)step(s,{},1/60);const pulse=s.events.find(e=>e.type==='domainPulse');assert.ok(pulse.hit>=1);assert.equal(pulse.defeated,pulse.hit);assert.ok(s.events.some(e=>e.type==='message'&&e.text.includes('struck')));const a=unlocked();act(a,'domain');for(let i=0;i<80;i++)step(a,{},1/60);assert.equal(a.events.find(e=>e.type==='domainPulse').hit,0);assert.ok(a.events.some(e=>e.text==='KEK DOMAIN · No enemies in reach.'));});
test('guardian cast locks facing and protects Crown while dealing one pulse',()=>{for(const face of [-1,1]){const s=unlocked();s.player.x=2250;enterWorld(s,'frozen');s.enemies.forEach(e=>{e.dead=true;s.approachCleared.push(e.id);});s.player.x=2250;enterArena(s);s.enemies.forEach(e=>{e.dead=true;s.approachCleared.push(e.id);});s.player.x=2250;enterArena(s);s.player.x=1900;s.player.face=face;const hp=s.player.hp;assert.equal(act(s,'domain'),true);for(let i=0;i<140;i++)step(s,{left:face===1,right:face===-1},1/60);assert.equal(s.player.x,1900);assert.equal(s.player.face,face);assert.equal(s.player.hp,hp);assert.equal(s.enemies.find(e=>e.boss).hp,110);assert.equal(s.events.filter(e=>e.type==='domainPulse').length,1);}});

test('Domain readiness matches the action gate during recovery and low resources',()=>{for(const patch of [{},{hurt:.1},{attack:.1},{dash:.1},{y:580},{sp:79},{domainCooldown:1}]){const s=unlocked();Object.assign(s.player,patch);const ready=domainReady(s);assert.equal(act(s,'domain'),ready);}});
