import test from 'node:test';import assert from 'node:assert/strict';
import {createState,act,step,snapshot} from '../core.js';
import {learn,skillPoints,stats,equip,addItem,useItem,upgradeGear,claimQuest,buyItem} from '../systems.js';
import {heroFrame,Renderer} from '../render.js';import {ANCHORS} from '../art-layout.js';
const tick=(s,n)=>{for(let i=0;i<n;i++)step(s,{},1/60);};
test('Warp Step plants, phases, lands and cannot stack',()=>{const s=createState(),x=s.player.x;act(s,'dash');assert.equal(act(s,'dash'),false);tick(s,3);assert.equal(s.player.x,x);assert.equal(heroFrame(s.player,0).col,0);tick(s,9);assert.ok(s.player.x>x+230);tick(s,9);assert.equal(s.player.x,x+240);assert.equal(s.player.warp,null);assert.equal(s.player.y,590);});
test('stationary attacks and hit effects preserve camera',()=>{const s=createState();s.player.x=1400;const r=new Renderer({width:1280,getContext:()=>({})},{});r.camera=400;act(s,'attack');r.effect({type:'hit',x:1400,y:500,amount:22},s);tick(s,20);r.update(.3,s);assert.equal(s.player.x,1400);assert.equal(r.camera,400);assert.equal(r.shake,0);});
test('skill points and real stats survive save migration',()=>{const s=createState({version:1,xp:60,oath:true,training:3});assert.equal(skillPoints(s),1);assert.equal(learn(s,'warp'),true);assert.equal(learn(s,'blade'),false);assert.equal(stats(s).warpRange,275);const restored=createState(snapshot(s));assert.equal(restored.skills.warp,1);assert.equal(skillPoints(restored),0);assert.equal(restored.inventory.healthFlask,2);});
test('equipment, forge and consumables use owned items and currency',()=>{const s=createState();assert.equal(equip(s,'voidFang'),false);addItem(s,'frostFang');assert.equal(equip(s,'frostFang'),true);assert.equal(stats(s).attack,8);s.player.x=490;s.fragments=28;assert.equal(upgradeGear(s),true);assert.equal(stats(s).attack,12);assert.equal(buyItem(s,'healthFlask'),true);assert.equal(s.fragments,0);assert.equal(upgradeGear(s),false);assert.equal(useItem(s,'healthFlask'),false);s.player.hp=20;assert.equal(useItem(s,'healthFlask'),true);assert.equal(s.player.hp,65);assert.equal(s.inventory.healthFlask,2);assert.equal(createState(snapshot(s)).gearLevels.frostFang,1);});
test('quest rewards are claimable once across reloads',()=>{const s=createState({version:1,oath:true,training:3,xp:30});assert.equal(claimQuest(s,'firstCut'),true);assert.equal(s.xp,60);assert.equal(s.fragments,12);const loaded=createState(snapshot(s));assert.equal(claimQuest(loaded,'firstCut'),false);assert.equal(loaded.xp,60);});
test('every sprite has a finite sole anchor within its cell',()=>{for(const frames of Object.values(ANCHORS))for(const a of frames){assert.ok(a.x>0&&a.x<1);assert.ok(a.y>.6&&a.y<=1);}});

test('Warp cancels recovery only after a committed cut',()=>{const s=createState();act(s,'attack');tick(s,10);assert.equal(act(s,'dash'),false);assert.equal(s.player.sp,100);tick(s,9);assert.equal(act(s,'dash'),true);assert.equal(s.player.attack,0);assert.equal(s.player.queued,false);});
test('enemy windups lock direction and do not hit behind their warned arc',()=>{const s=createState({version:1,oath:true,training:3});s.world='frozen';s.enemies=[{id:1,x:700,y:590,hp:65,maxHp:65,world:'frozen',face:-1,mode:'windup',timer:.2,stun:0,anim:0,hitFlash:0,dead:false,attackCount:0}];s.player.x=770;s.player.invuln=0;tick(s,14);assert.equal(s.enemies[0].face,-1);assert.equal(s.player.hp,100);});

test('academy gate emits a map request only after training',()=>{const s=createState();s.player.x=2250;act(s,'interact');assert.equal(s.events.some(e=>e.type==='gate'),false);s.oath=true;s.training=3;s.events=[];act(s,'interact');assert.equal(s.events.some(e=>e.type==='gate'),true);});

test('an attuned shrine revives the current run without restoring cleared enemies',async()=>{const {revive}=await import('../core.js');const s=createState({version:1,oath:true,training:3,xp:161,discoveries:['frozen'],world:'frozen'});s.enemies.slice(0,3).forEach(e=>{e.dead=true;e.hp=0;});s.approachCleared=[1,2,3];s.dead=true;s.player.hp=0;assert.equal(revive(s),true);assert.equal(s.world,'frozen');assert.equal(s.player.x,1360);assert.equal(s.player.hp,130);assert.equal(s.enemies.filter(e=>e.dead).length,3);assert.equal(s.zone,'approach');assert.ok(s.player.invuln>1);assert.equal(revive(s),false);});
