import {WEAPONS} from './campaign.js';
import {drawWeaponIcon} from './art.js';
import {ARMOR,SHIELDS} from './equipment.js';
import {drawArmor,drawShield} from './art.js';
import {ITEMS} from './adventure.js';
// Effects are presentation only. Damage remains in the fixed-step simulation.
export function drawCombatEffects(g,b){
  for(const e of b.effects){
    if(e.wardPulse){const t=1-e.life/.75;g.save();g.globalAlpha=(1-t)*.65;g.strokeStyle='#ffac5d';g.lineWidth=3;g.beginPath();g.ellipse(e.x,e.y,e.radius*t,e.radius*t*.42,0,0,Math.PI*2);g.stroke();g.restore();}
    else if(e.damageNumber){g.save();const age=.7-e.life,y=e.y-age*48;g.globalAlpha=Math.min(1,e.life*4);g.textAlign='center';g.font=e.source==='crown'?'bold 22px Georgia':e.source==='incoming'?'bold 20px Georgia':'bold 14px Georgia';g.fillStyle=e.source==='crown'?'#ffe59b':e.source==='incoming'?'#ffb4a0':'#eee8cf';g.strokeStyle='#17231f';g.lineWidth=3;g.strokeText(e.text,e.x,y);g.fillText(e.text,e.x,y);g.restore();}
    else if(e.reinforcement){g.save();g.globalAlpha=Math.min(1,e.life*3);g.font='bold 14px Georgia';g.textAlign='left';const text=`${e.team?'Enemy':'Crown'} reinforcement / ${e.text}`,width=g.measureText(text).width+20,x=Math.max(12,Math.min(1188-width,e.x-width/2)),y=e.y;g.fillStyle=e.team?'#492b25ee':'#153c2dee';g.strokeStyle=e.team?'#eeb08b':'#c9dea0';g.lineWidth=1;g.fillRect(x,y-19,width,28);g.strokeRect(x,y-19,width,28);g.fillStyle='#f4e6ba';g.fillText(text,x+10,y);g.restore();}
    else if(e.thrust){g.save();g.globalAlpha=e.life/.22;g.strokeStyle='#f4e6b5';g.lineWidth=3;g.beginPath();g.moveTo(e.x,e.y);g.lineTo(e.toX,e.toY);g.stroke();g.fillStyle='#fff1b8';g.beginPath();g.arc(e.toX,e.toY,4,0,Math.PI*2);g.fill();g.restore();}
    else if(e.armor){g.save();g.translate(e.x,e.y);g.globalAlpha=e.life/.25;g.strokeStyle='#c8e8da';g.lineWidth=2;for(let i=0;i<6;i++){const a=i*Math.PI/3,r=10+(1-e.life/.25)*12;g.beginPath();g.moveTo(Math.cos(a)*r,Math.sin(a)*r);g.lineTo(Math.cos(a)*(r+7),Math.sin(a)*(r+7));g.stroke();}g.restore();}
    else if(e.crush){const t=1-e.life/.3;g.save();g.translate(e.x,e.y);g.globalAlpha=1-t;g.strokeStyle='#d5e5a6';g.lineWidth=3;g.beginPath();g.ellipse(0,0,10+t*23,5+t*12,0,0,Math.PI*2);g.stroke();g.fillStyle='#deb97c';for(let i=0;i<7;i++){const a=i*Math.PI*2/7;g.fillRect(Math.cos(a)*t*32,Math.sin(a)*t*22,4,4);}g.restore();}
    else if(e.slash){const progress=1-e.life/.22;g.save();g.translate(e.x,e.y);g.scale(e.facing??1,1);g.strokeStyle=e.hero?'#ffe3a6':'#f0cf9a';g.globalAlpha=Math.min(1,e.life*7);g.lineWidth=e.hero?5:3;g.beginPath();g.arc(0,0,e.hero?(e.weapon==='dagger'?20:35):23,-1.2+progress*.7,1.2+progress*.7);g.stroke();for(let i=0;i<5;i++){const a=i*1.1+progress;g.fillStyle='#ffd785';g.fillRect(Math.cos(a)*progress*40,Math.sin(a)*progress*30,3,3);}g.restore();}
    else if(e.heal){g.save();g.globalAlpha=Math.min(1,e.life*3);g.strokeStyle='#ffe8a0';g.shadowColor='#fff4bc';g.shadowBlur=10;g.lineWidth=3;g.beginPath();g.moveTo(e.x,e.y);g.quadraticCurveTo((e.x+e.toX)/2,Math.min(e.y,e.toY)-25,e.toX,e.toY);g.stroke();g.strokeStyle='#a4f39a';g.lineWidth=2;g.beginPath();g.ellipse(e.toX,e.toY+55,24+(1-e.life/.45)*12,9,0,0,Math.PI*2);g.stroke();g.restore();}
    else if(e.spell){const t=1-e.life/.35,x=e.x+(e.toX-e.x)*t,y=e.y+(e.toY-e.y)*t;g.save();g.fillStyle=e.spell==='holy'?'#fff2a0':'#c284ff';g.shadowColor=g.fillStyle;g.shadowBlur=18;g.beginPath();g.arc(x,y,7,0,Math.PI*2);g.fill();g.strokeStyle=g.fillStyle;g.lineWidth=3;g.beginPath();g.moveTo(x-(e.toX-e.x)*.08,y-(e.toY-e.y)*.08);g.lineTo(x,y);g.stroke();g.restore();}
    else if(e.arrow){const t=1-e.life/.25,dx=e.toX-e.x,dy=e.toY-e.y,angle=Math.atan2(dy,dx);g.save();g.translate(e.x+dx*t,e.y+dy*t);g.rotate(angle);g.strokeStyle='#f6df9f';g.lineWidth=2;g.beginPath();g.moveTo(-20,0);g.lineTo(2,0);g.moveTo(-4,-4);g.lineTo(2,0);g.lineTo(-4,4);g.stroke();g.restore();}
    else if(e.ring){const t=1-e.life/(e.text==='SWEEP'?.55:.7);g.save();g.translate(e.x,e.y);g.strokeStyle=e.text==='SWEEP'?'#ffe4a9':'#a8f3a1';g.globalAlpha=1-t;g.lineWidth=5;g.beginPath();g.ellipse(0,0,e.ring*(.5+t*.5),e.ring*(.25+t*.25),0,0,Math.PI*2);g.stroke();g.font='bold 17px Georgia';g.textAlign='center';g.fillStyle=g.strokeStyle;g.fillText(e.text,0,-65-t*20);g.restore();}
    else{g.save();g.globalAlpha=Math.min(1,e.life*3);g.fillStyle=e.wardHeal?'#ffbe77':e.healing?'#baf4ad':'#fff0bf';g.strokeStyle='#2b2218';g.lineWidth=3;g.font='bold 18px Georgia';g.textAlign='center';g.strokeText(e.text,e.x,e.y-(.6-e.life)*45);g.fillText(e.text,e.x,e.y-(.6-e.life)*45);g.restore();}
  }
}
export function showBattleReport(report,onTown,onEquipment){
  const root=document.getElementById('battle-report');root.replaceChildren();root.hidden=!report;if(!report)return;
  const title=document.createElement('strong');title.textContent=`${report.won?'VICTORY':'WITHDRAWAL'} / ${report.name}`;
  const details=document.createElement('span');details.textContent=`+${report.gold} gold · ${report.survivors} survived · ${report.losses} lost${report.won?` · ${report.promotions} promoted`:''}${report.loot?.length?' / Loot: '+report.loot.map(id=>ITEMS[id].name).join(', '):''}`;
  const button=document.createElement('button');button.textContent='Return to Crownhaven';button.onclick=onTown;
  const dismiss=document.createElement('button');dismiss.textContent='Dismiss report';dismiss.className='quiet';dismiss.onclick=()=>{root.hidden=true;};
  root.append(title,details);
  if(report.mission){const objective=document.createElement('span');objective.textContent=`${report.mission.title}: ${report.mission.text}${report.mission.bonus?` / +${report.mission.bonus} objective gold included above`:''}.`;root.append(objective);}
  if(report.roll?.length){const total=report.roll.reduce((sum,row)=>({deployed:sum.deployed+(row.deployed??0),reserve:sum.reserve+(row.reserve??0)}),{deployed:0,reserve:0});const note=document.createElement('span');note.textContent=`${total.deployed} soldiers deployed / ${total.reserve} returned without deploying. Only deployed survivors earn victory experience.`;root.append(note);}
  for(const id of report.equipment??[]){const item=SHIELDS[id],row=document.createElement('div'),icon=document.createElement('canvas'),label=document.createElement('span');row.className='equipment-loot';icon.width=70;icon.height=95;drawShield(icon.getContext('2d'),id,35,47,.75);label.textContent=`Recovered: ${item.name} / +${item.health} maximum health. Open Inventory to equip for your next battle.`;row.append(icon,label);root.append(row);}
  for(const id of report.armorLoot??[]){const item=ARMOR[id],row=document.createElement('div'),icon=document.createElement('canvas'),label=document.createElement('span');row.className='equipment-loot';icon.width=80;icon.height=95;drawArmor(icon.getContext('2d'),id,40,47,70,85);label.textContent=`Recovered: ${item.name} / reduces incoming damage by ${item.reduction}. Open Inventory to equip for your next battle.`;row.append(icon,label);root.append(row);}
  for(const id of report.weaponLoot??[]){const item=WEAPONS[id],row=document.createElement('div'),icon=document.createElement('canvas'),label=document.createElement('span');row.className='equipment-loot';icon.width=80;icon.height=120;drawWeaponIcon(icon.getContext('2d'),id,40,60,105);label.textContent=`Recovered: ${item.name}. Added to your armory; open Inventory to equip.`;row.append(icon,label);root.append(row);}
  if(report.roll?.length){const roll=document.createElement('div');roll.className='battle-roll';for(const row of report.roll){const p=document.createElement('div');p.textContent=`${row.name}: ${row.survived} returned / ${row.lost} fallen / ${row.deployed} deployed / ${row.reserve} unused reserves${row.ranks.length?' / '+row.ranks.map(r=>`${r.count} ${r.name}`).join(', '):''}`;roll.append(p);}root.append(roll);}
  for(const quest of report.quests??[]){const note=document.createElement('span');note.textContent=`Ready to report: ${quest.name}. Return to ${quest.town} for ${quest.reward} gold.`;root.append(note);}
  if(report.newPoints){const level=document.createElement('span');level.textContent=`Crown gained ${report.newPoints} skill points. Open the Crown scroll to allocate them.`;root.append(level);}
  if(report.campaignComplete){const finale=document.createElement('span');finale.textContent='The Emerald Crown restored. Visit a settlement hall to read your campaign chronicle; remaining contracts stay available.';root.append(finale);}
  if(onEquipment&&[...(report.weaponLoot??[]),...(report.equipment??[]),...(report.armorLoot??[])].length){const inspect=document.createElement('button');inspect.textContent='Inspect recovered equipment';inspect.onclick=onEquipment;root.append(inspect);}
  root.append(button,dismiss);
}
