import {enemyAtPoint} from './battle-targeting.js';
import {missionHint,missionProgress,missionReport} from './missions.js';
import {missionProps} from './mission-art.js';
import {issueOrder,formationTarget} from './formation.js';
import {awardWeapon} from './gear-progression.js';
import {WEAPONS} from './campaign.js';
import {crownAppearance} from './crown-equipped.js';
import {extraWeaponImage,drawShield,drawHeldWeapon} from './art.js';
import {recordBattle} from './chronicle.js';
import {ORDER_TEXT} from './orders.js';
import {ARMOR,SHIELDS,awardArmor,awardEquipment,equipArmor,equipShield} from './equipment.js';
import {heroStats} from './hero-stats.js';
import {battleRoll} from './battle-roll.js';
import {nearbyInteraction} from './town-interaction.js';
import {newTownHero,stepTownHero,setTownDestination} from './town-movement.js';
import {townPeople,townPersonAt,residentImage} from './town-life.js';
import {createAudio} from './audio.js';
import {configureEncounter} from './encounters.js';
import {settlementTheme,settlementLandmarks} from './settlements.js';
import {SAVE_KEY,TROOPS,reserveTroop,prioritizeTroop,dismissTroop,newCampaign,migrateSave,recruit,upgrade,canMarch,settle,equipWeapon} from './campaign.js';
import {hydrateAdventure,allocate,abandonQuest,acceptQuest,claimQuest,markQuestVictory,lootBattle,sellItem,usePotion,buyDraught,QUESTS,points} from './adventure.js';
import {createBattle,stepBattle,ability,collectObjective} from './combat.js';
import {drawTown,castleSoldiers,armorImage,shieldImage,equipmentImage,environmentSoldiers,orderSoldiers,soldiers,townImage,settlementImage,corruptedImage,winterImage,frontierImage} from './art.js';
import {showBattleReport} from './feedback.js';
import {createBattleRenderer} from './scene.js';
import {renderScroll} from './panel.js';
import {NODES,ROADS,startTravel,stepTravel,drawWorld,mapImage,landmarks,regionalLandmarks,camera,centerCamera,nodeAt,worldPoint,frameRoute} from './world.js';
let gearTab='weapon';let requestedService=null;let townHero=newTownHero();const sound=createAudio();window.addEventListener('pointerdown',sound.unlock,{capture:true});window.addEventListener('keydown',sound.unlock,{capture:true});
const $=id=>document.getElementById(id),canvas=$('game'),g=canvas.getContext('2d');
let state=newCampaign();try{const migrated=migrateSave(JSON.parse(localStorage.getItem(SAVE_KEY)));if(migrated)state=migrated;}catch{}
hydrateAdventure(state);if(!NODES.some(n=>n.id===state.location))state.location='home';
let selected=state.location,battle=null,paused=false,scroll=null,townMode=isSettlement(),townService='castle',travel=null,keys={},hover=null,last=0,acc=0,report=null,pauseBeforeScroll=false,drag=null,toastUntil=0;
const crown=new Image();crown.src='assets/crown-base-v2.png';crown.onload=()=>ui();const battleImage=new Image();battleImage.src='assets/battlefield-v2.png';const forestImage=new Image();forestImage.src='assets/forest-v1.png';
const ruinsImage=new Image();ruinsImage.src='assets/moonwell-v1.png';
const renderBattle=createBattleRenderer(g,crown,battleImage,forestImage,ruinsImage);
centerOnCrown();
function isSettlement(){const n=NODES.find(n=>n.id===state.location);return !!n&&(!n.battle||state.owned.includes(n.id));}
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch{toast('Saving is unavailable in this browser.');}}
function toast(message){$('toast').textContent=message;$('toast').className='show';toastUntil=performance.now()+3200;}
function button(parent,label,fn,disabled=false){const b=document.createElement('button');b.textContent=label;b.disabled=disabled;b.onclick=()=>{fn();if(battle&&!scroll)canvas.focus();};parent.append(b);return b;}
function openScroll(mode){requestedService=null;keys={};townHero.path=[];townHero.target=null;townHero.moving=false;if(!scroll&&battle){pauseBeforeScroll=paused;paused=true;keys={};}if(mode==='forge'&&gearTab==='loot')gearTab='weapon';scroll=mode;sound.cue('scroll');ui();$('scroll-panel').scrollTop=0;$('close-scroll').focus();}
function closeScroll(){if(battle&&scroll)paused=pauseBeforeScroll;scroll=null;ui();canvas.focus();}
function mutate(fn){if(fn()===false){toast('This action is not available yet.');return;}sound.cue(scroll==='forge'?'forge':'reward');save();ui();}
function world(){if(battle)return;requestedService=null;closeScroll();townMode=false;centerOnCrown();ui();}
function centerOnCrown(){const p=travel??NODES.find(n=>n.id===state.location);centerCamera(p.x,p.y);}
function beginTravel(id){if(battle||travel)return;const t=startTravel(state.location,id);if(!t){toast('Crown is already here.');return;}travel=t;selected=id;townMode=false;report=null;showBattleReport(null);closeScroll();ui();}
function enterTown(){if(!isSettlement()||travel)return;townMode=true;townHero=newTownHero();townService='castle';openScroll('hall');}
function approachService(place){const destination={x:place.x,y:Math.min(555,Math.max(275,place.id==='questgiver'?place.y:place.y+50))};const id=place.id==='questgiver'?'market':place.id;if(Math.hypot(townHero.x-destination.x,townHero.y-destination.y)<=90){service(id);return;}setTownDestination(townHero,destination);requestedService={...destination,id};}
function service(id){if(!isSettlement()||battle||travel)return;requestedService=null;const mode={castle:'hall',market:'board',gate:'world',barracks:'barracks',forge:'forge'}[id]??id;if(mode==='world'){world();return;}townService=id;sound.cue(mode==='forge'?'forge':'service');openScroll(mode);}
function togglePause(){if(!battle||scroll)return;paused=!paused;keys={};ui();}
function setOrder(order){if(!battle||paused)return;issueOrder(battle,order);ui();}
function drink(){if(!battle||paused)return;if(usePotion(state,battle)){sound.cue('rally');save();ui();}else toast('Carry a healing draught and use it when wounded.');}
function cast(key){if(battle&&!paused)ability(battle,key);}
function march(){const n=NODES.find(n=>n.id===state.location);if(!n?.battle||!canMarch(state,n.battle)||travel)return;report=null;showBattleReport(null);closeScroll();battle=createBattle(state,n.battle);battle.destination=n.id;configureEncounter(battle,n.id);if(n.id==='ruins'&&state.quests.relic==='active')battle.objective={x:970,y:490,unlocked:false,collected:false,name:'Stolen harbor cargo'};battle.environment=n.id==='highpass'?'winter':n.corrupted?'volcanic':n.kind==='forest'?'forest':n.kind==='ruins'?'ruins':'fortress';battle.attributes={...state.attributes};const h=battle.hero,stats=heroStats(state);Object.assign(h,{shield:state.shield,damage:stats.damage,max:stats.max,hp:stats.max,speed:stats.speed,attackCooldown:stats.attackCooldown});townMode=false;paused=false;keys={};ui();canvas.focus();}
function finish(won){if(!battle)return;sound.cue(won?'victory':'defeat');const destination=battle.destination,survivors=[...battle.units,...(battle.reserves??[])].filter(u=>!u.hero&&u.team===0&&u.hp>0).map(u=>({type:u.type,xp:u.xp??0,origin:u.origin??'home',reserve:!!u.reserve}));const before=state.gold,oldLevel=state.level,newlyReady=won?QUESTS.filter(q=>q.target===destination&&state.quests[q.id]==='active'):[];const summary={won,mission:missionReport(battle,won),name:NODES.find(n=>n.id===destination).name,survivors:survivors.length,losses:state.army.length-survivors.length,promotions:won?survivors.filter(u=>u.xp<3&&!u.reserve).length:0};settle(state,battle.site,won,survivors);if(won){state.gold+=summary.mission?.bonus??0;markQuestVictory(state,destination);summary.loot=lootBattle(state,battle.site);summary.equipment=awardEquipment(state,battle.site);summary.armorLoot=awardArmor(state,battle.site);summary.weaponLoot=awardWeapon(state,destination);toast('Battle loot added to your inventory.');}summary.gold=state.gold-before;if(won)state.journal=`Victory at ${summary.name}! +${summary.gold} gold. ${summary.mission?summary.mission.text+'. ':''}${summary.survivors} soldiers returned.`;summary.roll=battleRoll([...battle.units,...(battle.reserves??[])],won);summary.quests=newlyReady.map(q=>({name:q.name,reward:q.reward,town:NODES.find(n=>n.id===q.board).name}));summary.newPoints=Math.max(0,state.level-oldLevel)*2;summary.campaignComplete=won&&destination==='keep';recordBattle(state,summary,[...(summary.equipment??[]).map(id=>SHIELDS[id].name),...(summary.armorLoot??[]).map(id=>ARMOR[id].name),...(summary.weaponLoot??[]).map(id=>WEAPONS[id].name)].join(', '));report=summary;battle=null;paused=false;scroll=null;selected=state.location;townMode=false;save();ui();showBattleReport(report,()=>beginTravel('home'),()=>{gearTab=report.weaponLoot?.length?'weapon':report.armorLoot?.length?'armor':'shield';showBattleReport(null);openScroll('inventory');});}
function reset(){if(!confirm('Replace only your Pepe Feudalism campaign?'))return;state=hydrateAdventure(newCampaign());battle=null;travel=null;scroll=null;paused=false;report=null;selected='home';townMode=true;townService='castle';showBattleReport(null);save();ui();}
function ui(){
 const appearance=crownAppearance(state),source=appearance.src;
 crown.bakedGear=appearance.baked;crown.wornArmor=appearance.worn;crown.renderSet=appearance.key;
 if(crown.getAttribute('src')!==source)crown.src=source;

 $('location').textContent=battle?NODES.find(n=>n.id===state.location).name:townMode?NODES.find(n=>n.id===state.location).name:'The Emerald Marches';$('treasury').textContent=`${state.gold} gold / Lv ${state.level}`;
 $('character-toggle').textContent=`Crown${points(state)?' / '+points(state)+' points':''}`;$('quests-toggle').textContent=`Quests / ${Object.values(state.quests).filter(x=>x==='active'||x==='ready').length}`;
 $('map-tools').hidden=townMode||!!battle;$('map-toggle').disabled=!!battle||!!travel;
 $('controls').replaceChildren();if(battle){for(const [i,order]of ['follow','hold','attack','retreat'].entries()){const b=button($('controls'),`${i+1} / ${order}`,()=>setOrder(order));b.title=ORDER_TEXT[order];b.setAttribute('aria-pressed',String(battle.order===order));if(battle.order===order)b.className='active-order';}button($('controls'),paused?'Resume battle':'Pause battle',togglePause).id='pause-battle';button($('controls'),'Q / Sweep',()=>cast('q')).id='ability-q';button($('controls'),'E / Rally',()=>cast('e')).id='ability-e';if(battle.objective||battle.mission?.type==='rescue')button($('controls'),battle.objective?'F / Recover cargo':'F / Free herbalist',()=>{if(!paused&&!collectObjective(battle))toast(missionHint(battle));}).id='objective-action';button($('controls'),`R / Draught (${state.inventory.filter(id=>id==='potion').length})`,drink,paused||!state.inventory.includes('potion')||battle.hero.hp>=battle.hero.max).id='quick-heal';button($('controls'),'Withdraw',()=>finish(false));}
 else if(townMode){button($('controls'),'Quest board',()=>service('board'));button($('controls'),'Barracks',()=>service('barracks'));button($('controls'),'Forge',()=>service('forge'));button($('controls'),'March Gate',world);}
 else if(travel){const span=document.createElement('span');span.textContent=`Marching to ${NODES.find(n=>n.id===travel.to).name}`;$('controls').append(span);}else button($('controls'),'Current destination',()=>{selected=state.location;openScroll('location');});
 renderScroll({state,crown,battle,scroll,selected,travel,gearTab,button,act:{chooseGearTab:id=>{gearTab=id;ui();$('panel-body').querySelector('.gear-tabs button[aria-pressed="true"]')?.focus({preventScroll:true});},serviceInventory:()=>openScroll('inventory'),soundEnabled:sound.snapshot().enabled,toggleSound:()=>{sound.toggle();ui();},inSettlement:isSettlement()&&!travel,buyDraught:()=>mutate(()=>buyDraught(state,isSettlement()&&!battle&&!travel)),allocate:key=>mutate(()=>allocate(state,key)),armor:id=>mutate(()=>!battle&&!travel&&equipArmor(state,id,isSettlement())),shield:id=>mutate(()=>!battle&&!travel&&equipShield(state,id,isSettlement())),equip:id=>mutate(()=>!battle&&!travel&&equipWeapon(state,id)),recruit:id=>mutate(()=>recruit(state,id)),reserve:index=>mutate(()=>reserveTroop(state,index,isSettlement()&&!battle&&!travel)),prioritize:index=>mutate(()=>prioritizeTroop(state,index,isSettlement()&&!battle&&!travel)),dismiss:index=>mutate(()=>dismissTroop(state,index,isSettlement()&&!battle&&!travel)),upgrade:()=>mutate(()=>upgrade(state)),sell:index=>mutate(()=>sellItem(state,index)),potion:()=>mutate(()=>usePotion(state,battle)),abandon:id=>mutate(()=>!battle&&!travel&&abandonQuest(state,id)),accept:id=>mutate(()=>acceptQuest(state,id,state.location)),claim:id=>mutate(()=>claimQuest(state,id,state.location)),track:id=>{world();selected=id;frameRoute(state.location,id);openScroll('location');},service,world,travel:beginTravel,enterTown,march,reset}});
}
for(const [id,mode]of [['character-toggle','character'],['inventory-toggle','inventory'],['quests-toggle','quests'],['army-toggle','army'],['settings-toggle','guide']])$(id).onclick=()=>scroll===mode?closeScroll():openScroll(mode);
$('map-toggle').onclick=world;$('close-scroll').onclick=closeScroll;$('shade').onclick=closeScroll;
function zoom(delta){camera.zoom=Math.max(.35,Math.min(1.15,camera.zoom+delta));centerCamera(camera.x,camera.y);}
$('zoom-in').onclick=()=>zoom(.12);$('zoom-out').onclick=()=>zoom(-.12);$('overview').onclick=()=>{camera.zoom=.35;centerCamera(1500,900);};$('follow').onclick=centerOnCrown;
function point(e){const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/1200,r.height/640),ox=(r.width-1200*scale)/2,oy=(r.height-640*scale)/2;return {x:(e.clientX-r.left-ox)/scale,y:(e.clientY-r.top-oy)/scale,scale};}
canvas.addEventListener('pointerdown',e=>{if(scroll||report&&!$('battle-report').hidden)return;const p=point(e);canvas.focus();if(battle){if(paused)return;const enemy=enemyAtPoint(battle.units,p);battle.attack=!!enemy;battle.targetId=enemy?.id??null;battle.target=enemy?null:{x:Math.max(35,Math.min(1165,p.x)),y:Math.max(230,Math.min(600,p.y))};}else if(townMode){const person=townPersonAt(NODES.find(n=>n.id===state.location),last/1000,p);if(person){approachService(person);return;}const place=settlementLandmarks(NODES.find(n=>n.id===state.location)).find(n=>Math.hypot(n.x-p.x,n.y+20-p.y)<90);if(place)approachService(place);else{requestedService=null;setTownDestination(townHero,p);}}else{drag={start:p,last:p,moved:false};canvas.setPointerCapture(e.pointerId);}});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(drag&&!townMode&&!battle){const dx=p.x-drag.last.x,dy=p.y-drag.last.y;if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>8)drag.moved=true;if(drag.moved&&!travel)centerCamera(camera.x-dx/camera.zoom,camera.y-dy/camera.zoom);drag.last=p;}hover=townMode&&townPersonAt(NODES.find(n=>n.id===state.location),last/1000,p)?'market':townMode?settlementLandmarks(NODES.find(n=>n.id===state.location)).find(n=>Math.hypot(n.x-p.x,n.y+20-p.y)<90)?.id:null;canvas.style.cursor=hover||!townMode&&!battle&&nodeAt(p)?'pointer':'default';});
canvas.addEventListener('pointerup',e=>{if(drag){if(!drag.moved&&!travel){const n=nodeAt(point(e));if(n){selected=n.id;openScroll('location');}}drag=null;}});
canvas.addEventListener('wheel',e=>{if(!battle&&!townMode&&!scroll){e.preventDefault();zoom(e.deltaY<0?.08:-.08);}},{passive:false});
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='escape'){e.preventDefault();if(scroll)closeScroll();return;}if(scroll&&k==='tab'){const controls=[...$('scroll-panel').querySelectorAll('button:not(:disabled)')];const first=controls[0],end=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();end.focus();}else if(!e.shiftKey&&document.activeElement===end){e.preventDefault();first.focus();}return;}if(e.repeat)return;if(['c','i','j','m'].includes(k)){e.preventDefault();if(k==='m')world();else{const mode={c:'character',i:'inventory',j:'quests'}[k];scroll===mode?closeScroll():openScroll(mode);}return;}if(scroll)return;if(townMode&&k==='f'){e.preventDefault();const near=nearbyInteraction(NODES.find(n=>n.id===state.location),townHero,last/1000);if(near)service(near.service);return;}if(townMode&&['w','a','s','d'].includes(k)){e.preventDefault();requestedService=null;keys[k]=true;return;}if(battle&&[' ','w','a','s','d','q','e','f','r','p','1','2','3','4'].includes(k)){e.preventDefault();keys[k]=true;if(k==='q'||k==='e')cast(k);if(k==='f'&&!paused){if(!collectObjective(battle))toast(missionHint(battle));}if(k==='r')drink();if(k==='p')togglePause();if('1234'.includes(k))setOrder(['follow','hold','attack','retreat'][Number(k)-1]);}else if(!battle&&!townMode&&['+','=','-'].includes(k))zoom(k==='-'?-.1:.1);});
window.addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false;});window.addEventListener('blur',()=>{keys={};if(battle){paused=true;if(scroll)pauseBeforeScroll=true;}});
function frame(time){const dt=Math.min((time-last)/1000,.1);last=time;if(travel&&!scroll){if(stepTravel(travel,dt)){state.location=travel.to;selected=travel.to;travel=null;save();sound.cue('arrival');toast(`Arrived at ${NODES.find(n=>n.id===state.location).name}`);openScroll('location');}else centerCamera(travel.x,travel.y);}
 if(battle&&!paused){acc+=dt;while(acc>=1/60&&battle){stepBattle(battle,1/60,keys);acc-=1/60;if(battle.result)finish(battle.result==='victory');}}else acc=0;
 if(townMode&&!scroll){stepTownHero(townHero,dt,keys);if(requestedService&&Math.hypot(townHero.x-requestedService.x,townHero.y-requestedService.y)<=40){const id=requestedService.id;requestedService=null;service(id);}}
 sound.update(battle??(townMode?{hero:townHero,effects:[]}:null),travel,time/1000,paused||!!scroll);
 if(battle){renderBattle(battle,paused);const objective=$('objective-action');if(objective){const progress=missionProgress(battle);objective.disabled=paused||!!progress?.complete;if(progress)objective.textContent=`F / Free herbalist (${progress.completed}/${progress.total})`;}const pauseButton=$('pause-battle');if(pauseButton)pauseButton.textContent=paused?'Resume battle':'Pause battle';const heal=$('quick-heal');if(heal)heal.disabled=paused||!state.inventory.includes('potion')||battle.hero.hp>=battle.hero.max;for(const key of ['q','e']){const b=$('ability-'+key);if(b){b.disabled=paused||battle[key]>0;b.textContent=`${key.toUpperCase()} / ${key==='q'?'Sweep':'Rally'}${battle[key]>0?' / '+battle[key].toFixed(1)+'s':''}`;}}}else if(townMode)drawTown(g,hover,townService,time/1000,NODES.find(n=>n.id===state.location),state,crown,townHero);else drawWorld(g,state,selected,travel,crown,time/1000,{drawShield,drawHeldWeapon});
 $('status').textContent=battle?`${battle.objective?.unlocked?'Recover marked cargo / F / ':''}${paused?'Paused / ':''}${Math.ceil(battle.hero.hp)} HP / ${battle.units.filter(u=>u.team===1&&u.hp>0).length} enemies on field`:travel?(scroll?'Travel paused / close scroll to continue':'Crown is traveling'):townMode?(nearbyInteraction(NODES.find(n=>n.id===state.location),townHero,time/1000)?.label?'F / '+nearbyInteraction(NODES.find(n=>n.id===state.location),townHero,time/1000).label:'WASD / ground click to walk • approach a resident or building'):`At ${NODES.find(n=>n.id===state.location).name}`;
 if(time>toastUntil)$('toast').className='';requestAnimationFrame(frame);
}
window.feudalismDiagnostics=()=>({crownArt:{source:crown.getAttribute('src'),look:crown.renderSet,baked:!!crown.bakedGear},requestedService:requestedService?{...requestedService}:null,nearby:townMode?nearbyInteraction(NODES.find(n=>n.id===state.location),townHero,last/1000):null,townHero:townMode?structuredClone(townHero):null,townPeople:townMode?townPeople(NODES.find(n=>n.id===state.location),last/1000):[],audio:sound.snapshot(),settlementScene:settlementTheme(NODES.find(n=>n.id===state.location)),buildingTargets:settlementLandmarks(NODES.find(n=>n.id===state.location)),campaign:structuredClone(state),scroll,selected,paused,townMode,townService,report:report?structuredClone(report):null,travel:travel?structuredClone(travel):null,camera:{...camera},nodes:NODES.map(n=>({...n})),activeMarkers:QUESTS.filter(q=>state.quests[q.id]==='active').map(q=>q.target),battle:battle?{targetId:battle.targetId,target:battle.target?{...battle.target}:null,time:battle.time,follow:battle.follow?{...battle.follow}:null,hold:{...battle.hold},encounter:battle.encounter??null,objective:battle.objective?{...battle.objective}:null,mission:battle.mission?structuredClone(battle.mission):null,missionProgress:missionProgress(battle),wardPulses:battle.effects.filter(e=>e.wardPulse).length,damageNumbers:battle.effects.filter(e=>e.damageNumber).map(e=>({source:e.source,text:e.text,x:e.x,y:e.y})),techniqueEffects:battle.effects.filter(e=>['STAGGER','PIERCE','CLEAVE'].includes(e.text)).map(e=>e.text),enemyReserves:battle.enemyReserves?.length??0,reserves:battle.reserves?.length??0,site:battle.site,destination:battle.destination,environment:battle.environment,hero:{weapon:battle.hero.weapon,x:battle.hero.x,y:battle.hero.y,hp:battle.hero.hp,max:battle.hero.max,damage:battle.hero.damage,speed:battle.hero.speed,swing:battle.hero.swing},q:battle.q,e:battle.e,order:battle.order,targets:battle.units.filter(u=>u.team===1&&u.hp>0).map(u=>({id:u.id,x:u.x,y:u.y,hp:u.hp,max:u.max,structure:u.structure??null,pulseCd:u.pulseCd??null,type:u.type,stagger:u.stagger??0,captain:u.captain??null})),allies:battle.units.filter(u=>u.team===0&&!u.hero).map(u=>({id:u.id,type:u.type,xp:u.xp,hp:u.hp,x:u.x,y:u.y,enemyId:u.enemyId??null,post:u.formationPost,target:formationTarget(battle,u)}))}:null,assetLoaded:crown.complete&&crown.naturalWidth>0,artLoaded:[missionProps,extraWeaponImage,crown,battleImage,forestImage,ruinsImage,castleSoldiers,armorImage,shieldImage,equipmentImage,environmentSoldiers,orderSoldiers,soldiers,townImage,settlementImage,corruptedImage,winterImage,frontierImage,residentImage,mapImage,landmarks,regionalLandmarks].every(i=>i.complete&&i.naturalWidth>0)});
soldiers.addEventListener('load',ui);ui();requestAnimationFrame(frame);
