// Authored local voices. Dialogue reads quest state; it grants no extra rewards.
export const RESIDENTS={
 greenmere:{name:'Herbalist Willow',role:'Keeper of the Gatherers’ Lodge',offer:'Our gatherers need Elderwood’s herbs, but raiders block the trail. Clear their camp and return here.',active:'Bring your archers. The grove offers little mercy to a scattered patrol.',ready:'The gatherers are home with their baskets. Your promised payment is ready.',completed:'Our herb trail is open. Your name is written in the lodge book.'},
 pearlport:{name:'Dockmaster Brine',role:'Master of the Northern Caravans',offer:'Salt is waiting on our docks while raiders hold Highpass. Clear the shrine for our northern caravan.',active:'Keep your army together in the snow. Report here when the pass is clear.',ready:'Our wagons can reach the snowbound villages. Pearlport has your reward.',completed:'The northern caravan sailed and the salt accounts are settled.'},
 snowcastle:{name:'Warden Snow',role:'Keeper of Wintercrown',offer:'Raiding bands have taken Highpass Shrine. Clear the mountain road and return here.',active:'The pass is narrow. Keep your warband together at the shrine.',ready:'Our messengers crossed the pass safely. Your reward is waiting.',completed:'Highpass is open again. Your patrol is recorded in Wintercrown.'},
 cinderford:{name:'Scout Ember',role:'Volcanic Frontier Watch',offer:'Ashveil raiders threaten the road below the volcano. Clear their grove before marching on Ashfang.',active:'Our scouts await word from Ashveil. Keep your supplies close.',ready:'The forest road is clear. Cinderford has gathered your reward.',completed:'Your banner protects the road to the volcanic frontier.'},
 home:{name:'Steward Rowan',role:'Keeper of Crown Hall',offer:'The Briar road has gone quiet. Our grain carts should have arrived yesterday.',active:'My runners saw your banner on the road. Clear the raiders, then come back to us.',ready:'The carts are moving again. Your payment is waiting beneath my seal.',completed:'Your name is spoken kindly in the market. The Briar road is open again.'},
 mossford:{name:'Warden Fern',role:'Elderwood Ranger',offer:'Bowmen have taken the ancient grove. They fire on anyone who approaches the spring.',active:'Watch the tree line. Those archers will punish a scattered warband.',ready:'The spring is ours again. Mossford owes you its thanks and your promised pay.',completed:'Our gatherers have returned to Elderwood. You gave this village its forest back.'},
 port:{name:'Harbormaster Mira',role:'Master of Tideharbor',offer:'Our stolen cargo lies at Moonwell. Defeat its guards and recover the marked chest.',active:'A battle alone will not bring our cargo home. Approach the chest and recover it before leaving.',ready:'You brought the harbor cargo back. The dockworkers pooled your reward.',completed:'The missing cargo is accounted for. Ships are loading beneath your banner again.'},
 sunspire:{name:'Castellan Aurell',role:'Keeper of Sunspire',offer:'Reedwatch commands the crossing. Take it, and our caravans can move east.',active:'A captured crossing matters more than scattered raiders. Break Reedwatch’s defense.',ready:'Your banner flies over the crossing. Sunspire will honor its promise.',completed:'The crossing is secured. Every eastbound caravan carries word of your victory.'},
 eastport:{name:'Captain Sable',role:'Eastwatch Harbor Guard',offer:'Varric the Thorn has fortified Jadefall. Take seasoned soldiers; his guard will hold its ground.',active:'Varric still stands between us and the forest road. Sharpen your blade before returning.',ready:'Varric has fallen. Our harbor guards can patrol the road again.',completed:'Jadefall’s captain is defeated. Your warband has earned a place in our harbor records.'},
 outpost:{name:'Marshal Reed',role:'Commander of the Crossing',offer:'Our eastern road remains exposed. Clear Jadefall so this garrison can hold the crossing.',active:'Keep your formation tight on the eastern patrol. Report here when Jadefall is cleared.',ready:'Your patrol has secured the road. The garrison has set aside your payment.',completed:'Your eastern patrol is entered in the garrison rolls. The crossing has its shield.'},
 keep:{name:'Chancellor Flint',role:'Steward of the Captured Keep',offer:'A banner is only a beginning. Clear Moonwell so travelers can trust this new peace.',active:'The Moonwell raiders still threaten our travelers. Finish the patrol, then return to the keep.',ready:'Moonwell is clear. We can finally call these roads peaceful.',completed:'Your patrol is recorded in the keep’s annals. Peace has work behind it now.'},
 frostford:{name:'Elder Rime',role:'Speaker of Frostford',offer:'Ashfang’s banner shadows the northern ridge. Take Reedwatch first, then bring down the keep.',active:'The northern villages await your victory. The keep will not fall to an unprepared army.',ready:'Ashfang’s banner is broken. Frostford will remember who brought this dawn.',completed:'The ridge belongs to the Emerald Crown. Your victory is carved into our village record.'}
};
export function residentDialogue(location,status){const resident=RESIDENTS[location];return resident?resident[status]??resident.offer:null;}
