import {test} from 'node:test';import assert from 'node:assert/strict';
import {newCampaign} from '../campaign.js';
import {hydrateAdventure,allocate,points,acceptQuest,markQuestVictory,claimQuest,lootBattle,sellItem,usePotion} from '../adventure.js';
import {NODES,route,startTravel,stepTravel} from '../world.js';
import {createBattle,ability} from '../combat.js';
test('every destination is connected, travel advances and ends at the destination',()=>{for(const n of NODES)assert.ok(route('home',n.id).length);const t=startTravel('home','eastport');let done=false;for(let i=0;i<2000&&!done;i++)done=stepTravel(t,1/60);assert.equal(done,true);const dest=NODES.find(n=>n.id==='eastport');assert.equal(t.x,dest.x);assert.equal(t.y,dest.y);});
test('skill points cannot exceed earned pool and ability stats affect combat',()=>{const s=hydrateAdventure(newCampaign());assert.equal(allocate(s,'STR'),false);s.level=2;assert.equal(points(s),2);assert.equal(allocate(s,'INT'),true);assert.equal(allocate(s,'WIS'),true);assert.equal(allocate(s,'VIT'),false);const b=createBattle(s,'hunt');b.attributes=s.attributes;const e=b.units.find(u=>u.team===1);e.x=b.hero.x;e.y=b.hero.y;ability(b,'q');assert.equal(e.hp,10);assert.equal(b.q,4.9);});
test('quest acceptance and reward require the issuing location and victory',()=>{const s=hydrateAdventure(newCampaign());assert.equal(acceptQuest(s,'briar','port'),false);assert.equal(acceptQuest(s,'briar','home'),true);assert.equal(claimQuest(s,'briar','home'),false);markQuestVictory(s,'hunt');assert.equal(s.quests.briar,'ready');assert.equal(claimQuest(s,'briar','port'),false);assert.equal(claimQuest(s,'briar','home'),true);assert.equal(s.gold,185);assert.equal(claimQuest(s,'briar','home'),false);});
test('loot inventory is bounded, trading removes items, healing consumes one',()=>{const s=hydrateAdventure(newCampaign());lootBattle(s,'hunt');assert.deepEqual(s.inventory,['jade','potion']);assert.equal(sellItem(s,0),true);assert.equal(s.gold,152);const b=createBattle(s,'hunt');assert.equal(usePotion(s,b),false);b.hero.hp=100;assert.equal(usePotion(s,b),true);assert.equal(b.hero.hp,180);assert.deepEqual(s.inventory,[]);s.inventory=Array(60).fill('jade');assert.deepEqual(lootBattle(s,'keep'),[]);});
