const {chromium}=require('C:/Users/Phantom Assassin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const {newCampaign}=await import('../campaign.js'),{hydrateAdventure}=await import('../adventure.js');const seed=hydrateAdventure(newCampaign());seed.location='ruins';seed.quests.relic='active';seed.inventory=['potion'];
 const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1500,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/pepe-feudalism/index.html');await page.evaluate(s=>localStorage.setItem('pepe-feudalism-campaign-v1',JSON.stringify(s)),seed);await page.reload();await page.waitForFunction(()=>window.feudalismDiagnostics?.().artLoaded);await page.getByRole('button',{name:'Current destination',exact:true}).click();await page.getByRole('button',{name:'Explore the ruins',exact:true}).click();
 const read=()=>page.evaluate(()=>window.feudalismDiagnostics());
 async function click(x,y){const r=await page.locator('#game').boundingBox(),s=Math.min(r.width/1200,r.height/640);await page.mouse.click(r.x+(r.width-1200*s)/2+x*s,r.y+(r.height-640*s)/2+y*s);}
 await page.keyboard.press('f');assert.equal((await read()).battle.objective.collected,false);await page.keyboard.down(' ');
 const until=Date.now()+60000;while(Date.now()<until){const d=await read();if(d.battle.objective.unlocked)break;const t=d.battle.targets.sort((a,b)=>Math.hypot(a.x-d.battle.hero.x,a.y-d.battle.hero.y)-Math.hypot(b.x-d.battle.hero.x,b.y-d.battle.hero.y))[0];if(t)await click(t.x,t.y-50);await page.keyboard.press('q');await page.keyboard.press('e');await page.waitForTimeout(250);}
 await page.keyboard.up(' ');let d=await read();assert.ok(d.battle.objective.unlocked);assert.equal(d.battle.environment,'ruins');assert.equal(d.campaign.quests.relic,'active');const beforeHeal=d.battle.hero.hp;assert.ok(beforeHeal<d.battle.hero.max);await page.keyboard.press('r');d=await read();assert.equal(d.battle.hero.hp,Math.min(d.battle.hero.max,beforeHeal+80));assert.equal(d.campaign.inventory.length,0);assert.equal(d.scroll,null);await page.screenshot({path:path.join(__dirname,'../docs/moonwell-objective-v7.png')});await click(970,490);await page.waitForFunction(()=>{const d=window.feudalismDiagnostics();return Math.hypot(d.battle.hero.x-970,d.battle.hero.y-490)<80});await page.keyboard.press('f');await page.waitForFunction(()=>window.feudalismDiagnostics().report?.won);d=await read();assert.equal(d.campaign.quests.relic,'ready');assert.equal(d.campaign.inventory.length,2);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'../docs/cargo-verification-v6.json'),JSON.stringify({result:'PASS',checks:['guard lock','actual combat','no premature quest completion','mouse approach','F recovery','victory and quest ready','loot'],errors},null,2));console.log('CARGO QA PASS');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
