const {chromium}=require('C:/Users/Phantom Assassin/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const {newCampaign}=await import('../campaign.js'),{hydrateAdventure}=await import('../adventure.js');const seed=hydrateAdventure(newCampaign());seed.location='jadeforest';seed.quests.jade='active';seed.army=['spearman','spearman','spearman','spearman','archer','archer'];seed.armyXp=seed.army.map(()=>1);seed.upgrade=1;
 const browser=await chromium.launch({channel:'msedge',headless:true}),page=await browser.newPage({viewport:{width:1500,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/pepe-feudalism/index.html');await page.evaluate(s=>localStorage.setItem('pepe-feudalism-campaign-v1',JSON.stringify(s)),seed);await page.reload();await page.waitForFunction(()=>window.feudalismDiagnostics?.().artLoaded);await page.getByRole('button',{name:'Current destination',exact:true}).click();assert.ok(await page.getByText('Scout report',{exact:true}).isVisible());assert.ok(await page.getByText('Varric the Thorn',{exact:true}).isVisible());await page.screenshot({path:path.join(__dirname,'../docs/scouting-scroll-v9.png')});await page.getByRole('button',{name:'Enter forest encounter',exact:true}).click();
 const read=()=>page.evaluate(()=>window.feudalismDiagnostics());
 async function click(x,y){const r=await page.locator('#game').boundingBox(),s=Math.min(r.width/1200,r.height/640);await page.mouse.click(r.x+(r.width-1200*s)/2+x*s,r.y+(r.height-640*s)/2+y*s);}
 let d=await read();assert.equal(d.battle.encounter,'Jadefall War Camp');assert.equal(d.battle.targets.length,6);assert.ok(d.battle.targets.some(u=>u.captain==='Varric the Thorn'));await page.keyboard.press('3');await page.screenshot({path:path.join(__dirname,'../docs/jadefall-camp-v8.png')});await page.keyboard.down(' ');
 const until=Date.now()+60000;while(Date.now()<until){d=await read();if(!d.battle)break;const t=d.battle.targets.sort((a,b)=>Math.hypot(a.x-d.battle.hero.x,a.y-d.battle.hero.y)-Math.hypot(b.x-d.battle.hero.x,b.y-d.battle.hero.y))[0];if(t)await click(t.x,t.y-50);await page.keyboard.press('q');await page.keyboard.press('e');await page.waitForTimeout(250);}
 await page.keyboard.up(' ');d=await read();assert.equal(d.report?.won,true);assert.equal(d.campaign.quests.jade,'ready');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'../docs/jadefall-verification-v8.json'),JSON.stringify({result:'PASS',checks:['regional roster','captain','real combat victory','quest ready'],errors},null,2));console.log('JADEFALL QA PASS');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
