import * as THREE from '../crown-pepe-3d/vendor/three.module.js';
import {createTempleScenery} from './temple-scenery.js';
import {createTrackView} from './track-view.js';
import assert from 'node:assert/strict';

// Asset fetching is stubbed; all meshes, instancing, world transforms and bounds are real Three.js.
class TextureLoader{load(path,onLoad){const texture=new THREE.Texture();onLoad(texture);return texture;}}
const scene=new THREE.Scene(),scenery=createTempleScenery({...THREE,TextureLoader},scene),track=createTrackView({...THREE,TextureLoader},scene);
const d={state:'running',distance:449,time:10,visualLane:1,magnet:0,turn:{announced:true,remaining:1,direction:'left',completed:0,visualBend:0},objects:[{type:'jade',lane:1,z:120,hit:false}]};
track.update(d,.04);const original=JSON.stringify(d);scenery.update(d,track.viewPose());assert.equal(JSON.stringify(d),original,'Scenery mutated runner state');
const root=scene.children.find(o=>o.name==='EmeraldFrogTempleScenery'),batches=root.children.filter(o=>o.isInstancedMesh),receipt=scenery.diagnostics();
assert.equal(receipt.loaded,true);assert.equal(receipt.assetsReady,true);assert.equal(receipt.error,null);assert.equal(receipt.terraces,28);assert.equal(receipt.shrines,12);assert.ok(receipt.meshCount>400&&receipt.meshCount<1350,'Scenery part budget');assert.ok(receipt.drawBatches<28,'Scenery draw-call budget');assert.equal(receipt.drawBatches,batches.length+1);assert.equal(batches.reduce((sum,b)=>sum+b.count,0)+1,receipt.renderInstances);
assert.equal(receipt.archGeometry,'sculpted-frog-mouth-curved-lips');assert.equal(receipt.brazierGeometry,'open-lathe-bowl');assert.equal(receipt.roofGeometry,'upturned-four-sided-pagoda');const roofBatch=batches.find(b=>b.geometry.userData.architecture==='upturned-four-sided-pagoda');assert.ok(roofBatch);const roofProfile=roofBatch.geometry.userData.profile;assert.ok(roofProfile.at(-1)[1]>roofProfile.at(-2)[1],'Roof eave must turn upward');const bowlBatch=batches.find(b=>b.geometry.type==='LatheGeometry');assert.ok(bowlBatch);assert.equal(bowlBatch.count,24);
assert.equal(receipt.guardianGeometry,'curved-lips-eyelids-nostrils-forward-feet');const guardians=[];root.traverse(o=>{if(o.userData.sculpture==='frog-guardian-with-lips-nostrils-feet')guardians.push(o);});assert.equal(guardians.length,14);for(const guardian of guardians){assert.equal(guardian.children.filter(m=>m.geometry.userData.sculpture==='curved-guardian-lip').length,3);assert.equal(guardian.children.filter(m=>m.geometry.userData.sculpture==='raised-guardian-eyelid').length,2);assert.equal(guardian.children.filter(m=>m.userData.sculpture==='forward-guardian-foot').length,2);assert.ok(guardian.children.filter(m=>m.userData.sculpture==='forward-guardian-foot').every(m=>m.position.z>.5));}
const guardianLipBatch=batches.find(b=>b.geometry.userData.sculpture==='curved-guardian-lip');assert.ok(guardianLipBatch);for(let i=0;i<guardianLipBatch.geometry.attributes.normal.count;i++)assert.ok(new THREE.Vector3().fromBufferAttribute(guardianLipBatch.geometry.attributes.normal,i).length()>.9);
const fireBatch=batches.find(b=>b.geometry.type==='ConeGeometry'&&b.material.isShaderMaterial);assert.ok(fireBatch);assert.equal(fireBatch.material.transparent,true);assert.equal(fireBatch.material.depthWrite,false);assert.equal(fireBatch.userData.noShadow,true);assert.equal(receipt.flameGeometry,'instanced-procedural-orange-fire');assert.equal(fireBatch.material.uniforms.simulationTime.value,d.time);assert.equal(receipt.flameTime,d.time);
const temple=root.children.find(g=>g.isGroup&&g.position.z===receipt.farTempleZ&&g.children.some(o=>o.geometry?.type==='TubeGeometry'));assert.ok(temple);assert.ok(temple.children.filter(o=>o.geometry?.type==='TubeGeometry').length>=5);root.updateMatrixWorld(true);const passage=new THREE.Box3(new THREE.Vector3(-3,0,-63),new THREE.Vector3(3,9,-55));for(const child of temple.children)if(child.isMesh&&child.geometry.userData.architecture!=='consolidated-sculpted-arch')assert.equal(new THREE.Box3().setFromObject(child).intersectsBox(passage),false,'Sculpted temple blocks its central passage');
const lipBatch=batches.find(b=>b.geometry.type==='TubeGeometry'&&b.material.isMeshStandardMaterial);assert.ok(lipBatch.material.roughness>=.6&&lipBatch.material.roughness<=.85);
assert.deepEqual(receipt.archConsolidation,{sourceCurves:4,savedDrawBatches:3});const merged=root.children.find(o=>o.isInstancedMesh&&o.geometry.userData.architecture==='consolidated-sculpted-arch');assert.ok(merged);const sourceCurves=temple.children.filter(o=>o.userData.consolidatedArch),sourceTriangles=sourceCurves.reduce((n,o)=>n+o.geometry.index.count/3,0);assert.equal(merged.geometry.attributes.position.count/3,sourceTriangles,'Consolidation removed sculpted detail');const matrix=new THREE.Matrix4();merged.getMatrixAt(0,matrix);matrix.premultiply(root.matrixWorld);for(let i=0;i<merged.geometry.attributes.position.count;i++){const p=new THREE.Vector3().fromBufferAttribute(merged.geometry.attributes.position,i).applyMatrix4(matrix);assert.equal(passage.containsPoint(p),false,'Merged arch enters passage');}
const water=root.children.find(o=>o.name==='TempleRippleWater');assert.equal(water.material.isShaderMaterial,true);assert.equal(water.material.fog,true);assert.equal(water.visible,true);assert.equal(water.material.uniforms.simulationTime.value,d.time);assert.equal(receipt.waterGeometry,'fogged-procedural-ripple-plane');assert.equal(receipt.waterTime,d.time);assert.equal(receipt.farTempleZ,-62);
const frozen=()=>({receipt:scenery.diagnostics(),flameTime:fireBatch.material.uniforms.simulationTime.value,waterTime:water.material.uniforms.simulationTime.value,waterHeading:water.material.uniforms.heading.value,waterNight:water.material.uniforms.night.value,root:root.matrixWorld.toArray(),instances:batches.map(o=>Array.from(o.instanceMatrix.array))});const torchPositions=scenery.torchPositions();assert.equal(torchPositions.length,2);assert.ok(torchPositions.every(p=>Math.abs(p.x)>7&&p.y>2&&p.z>=-19&&p.z<=-1),'Torch lights must follow nearest outer bowls');
assert.equal(receipt.waterDepth,'local-layered-noise-soft-crest');assert.equal(water.material.uniforms.depthContrast.value,.32);assert.equal(water.material.uniforms.glintStrength.value,.28);assert.ok(water.material.vertexShader.includes('surfaceLocal=p.xy'),'Water texture lost temple-local coordinates');assert.ok(water.material.fragmentShader.includes('depthWater(q*.055'),'Water depth lacks broad local variation');assert.ok(water.material.fragmentShader.includes('smoothstep(.36,.74,waterPatch)'),'Highlights remain continuous bright bands');
assert.deepEqual(receipt.waterContact,{foundations:12,halfWidth:2.7,halfDepth:2.4,band:.35,space:'temple-local'});const contacts=water.material.uniforms.foundationCenters.value,foundations=root.children.filter(g=>g.userData.shrineFoundation);assert.equal(contacts.length,12);assert.equal(foundations.length,12);foundations.forEach((g,i)=>assert.deepEqual(contacts[i].toArray(),[g.position.x,g.position.z]));assert.ok(water.material.fragmentShader.includes('vec2 rootXZ=vec2(q.x,-q.y-43.)'));assert.ok(water.material.fragmentShader.includes('vec2(2.7,2.4)'));assert.ok(water.material.fragmentShader.includes('smoothstep(.03,.35,outsideDistance)'));const contactFreeze=contacts.map(v=>v.toArray()),contactObjects=[...contacts];scenery.update(d,track.viewPose());assert.deepEqual(contacts.map(v=>v.toArray()),contactFreeze);contacts.forEach((v,i)=>assert.equal(v,contactObjects[i],'Contact uniform vector reallocated'));
const paused=frozen();for(let i=0;i<20;i++)scenery.update(d,track.viewPose());assert.deepEqual(frozen(),paused,'Pause changed scenery matrices or water/fire time');
d.distance=450;d.time=10.04;d.turn={announced:false,remaining:450,direction:'right',completed:1,visualBend:0};track.update(d,.04);d.distance=459;d.time=10.365;track.update(d,.04);const pose=track.viewPose();assert.equal(pose.active,true);scenery.update(d,pose);scene.updateMatrixWorld(true);
const road=scene.children.find(o=>o.name==='EmeraldTempleTrack').children.find(o=>o.name==='TempleOutgoingWorld');assert.deepEqual(root.matrixWorld.toArray(),road.matrixWorld.toArray(),'Scenery and outgoing track use different world basis');
assert.equal(water.material.uniforms.heading.value,pose.nextHeadingYaw,'Water normals must follow the outgoing temple basis');assert.equal(scenery.diagnostics().waterShading,'local-space-ripples-restrained-sun-glint');assert.equal(water.material.uniforms.simulationTime.value,d.time);assert.ok(water.material.uniforms.simulationTime.value>paused.waterTime,'Running water time did not advance');
assert.equal(fireBatch.material.uniforms.simulationTime.value,d.time);assert.ok(fireBatch.material.uniforms.simulationTime.value>paused.flameTime,'Running fire time did not advance');
const forwardScenery=new THREE.Vector3(0,0,-40).applyMatrix4(root.matrixWorld),forwardTrack=track.worldPosition(1,132,d);assert.ok(forwardScenery.x<pose.player.x);assert.ok(forwardTrack.x<pose.player.x);assert.ok(Math.abs(forwardScenery.z)<1e-7&&Math.abs(forwardTrack.z)<1e-7,'Forward architecture misses outgoing corridor');
const activeFreeze=frozen();scenery.update(d,pose);assert.deepEqual(frozen(),activeFreeze,'Paused active turn changed scenery');
const contactInverse=root.matrixWorld.clone().invert();foundations.forEach((g,i)=>{const actual=g.getWorldPosition(new THREE.Vector3()).applyMatrix4(contactInverse);assert.ok(Math.abs(contacts[i].x-actual.x)<1e-6&&Math.abs(contacts[i].y-actual.z)<1e-6,'Water contact does not follow turned shrine');});
d.time=10.7;track.update(d,.04);scenery.update(d,track.viewPose());assert.equal(root.rotation.y,0);assert.equal(root.position.x,0);assert.equal(scenery.diagnostics().pose.active,false);
class FailedTextureLoader{load(path,onLoad,onProgress,onError){onError(new Error('fixture load failure'));return new THREE.Texture();}}
const fallback=createTempleScenery({...THREE,TextureLoader:FailedTextureLoader},new THREE.Scene());fallback.update(d,track.viewPose());assert.equal(fallback.diagnostics().loaded,true);assert.equal(fallback.diagnostics().assetsReady,false);assert.ok(fallback.diagnostics().error.includes('using material colors'));
console.log(`SCENERY PASS: ${receipt.meshCount} modeled parts / ${receipt.drawBatches} batches, read-only state, pause matrices, matching turn basis, outgoing forward space, reset`);



const importedScene=new THREE.Scene(),imported=createTempleScenery({...THREE,TextureLoader},importedScene),model=new THREE.Group();
const importedMesh=new THREE.Mesh(new THREE.BoxGeometry(1,2,1),new THREE.MeshStandardMaterial());importedMesh.position.y=1;model.add(importedMesh);imported.update(d,{active:false,player:{x:0,z:0}});const initialBatches=importedScene.children[0].children.filter(o=>o.isInstancedMesh),initialCounts=initialBatches.map(o=>o.count),initialMatrices=initialBatches.map(o=>Array.from(o.instanceMatrix.array));imported.mountGuardianModel(model);imported.update(d,{active:false,player:{x:0,z:0}});
assert.equal(imported.diagnostics().guardianAsset.instances,14);assert.equal(imported.diagnostics().guardianGeometry,'blender-sculpted-guardian');assert.equal(imported.diagnostics().guardianAsset.drawBatches,1);assert.ok(imported.diagnostics().suppressedGuardianBatches>0,'Fallback-only guardian batches must stop rendering after import');assert.equal(imported.diagnostics().drawBatches,receipt.drawBatches+1-imported.diagnostics().suppressedGuardianBatches);
const importedRoot=importedScene.children.find(o=>o.name==='EmeraldFrogTempleScenery'),newBatch=importedRoot.children.filter(o=>o.isInstancedMesh).at(-1);assert.equal(newBatch.count,14);assert.equal(newBatch.castShadow,true);const importedMatrices=Array.from(newBatch.instanceMatrix.array);imported.update(d,{active:false,player:{x:0,z:0}});assert.deepEqual(Array.from(newBatch.instanceMatrix.array),importedMatrices,'Imported guardians move while paused');
assert.throws(()=>imported.mountGuardianModel(new THREE.Group()),/valid geometry/);
let reduced=0,savedTriangles=0;for(let i=0;i<initialBatches.length;i++){const b=initialBatches[i];if(!b.visible)continue;reduced+=initialCounts[i]-b.count;savedTriangles+=(initialCounts[i]-b.count)*(b.geometry.index?b.geometry.index.count:b.geometry.attributes.position.count)/3;let cursor=0;for(let j=0;j<b.count;j++){const retained=Array.from(b.instanceMatrix.array.slice(j*16,j*16+16));while(cursor<initialCounts[i]&&JSON.stringify(initialMatrices[i].slice(cursor*16,cursor*16+16))!==JSON.stringify(retained))cursor++;assert.ok(cursor<initialCounts[i],'Compaction changed retained transform or source order');cursor++;}}
assert.ok(reduced>100,'Mixed batches still contain hidden guardian instances');assert.equal(imported.diagnostics().compactedMixedInstances,reduced);assert.equal(imported.diagnostics().compactedMixedTriangles,savedTriangles);assert.ok(savedTriangles>10000,'Compaction did not save submitted triangles');
imported.mountGuardianModel(null);imported.update(d,{active:false,player:{x:0,z:0}});assert.equal(imported.diagnostics().guardianAsset,null);assert.equal(imported.diagnostics().compactedMixedInstances,0);assert.deepEqual(initialBatches.map(o=>o.count),initialCounts,'Fallback instance counts failed to restore');assert.deepEqual(initialBatches.map(o=>Array.from(o.instanceMatrix.array)),initialMatrices,'Fallback transforms failed to restore');assert.ok(initialBatches.every(o=>o.visible));console.log(`COMPACTION PASS: ${reduced} mixed fallback instances / ${savedTriangles} submitted triangles removed and fallback restored`);
console.log('BLENDER ADAPTER PASS: normalized shared instances, shadows, fallback validation and pause');

for(const distance of [0,35,200,450,850,1050]){
 scenery.update({...d,distance},{active:false,player:{x:0,z:0}});root.updateMatrixWorld(true);
 const shrines=root.children.filter(g=>g.userData.shrineFoundation);assert.equal(shrines.length,12);
 for(const shrine of shrines){
  const foundation=shrine.children.find(o=>o.userData.shrineSupport),support=new THREE.Box3().setFromObject(foundation),guardian=shrine.children.find(g=>g.userData.sculpture==='frog-guardian-with-lips-nostrils-feet'),body=new THREE.Box3().setFromObject(guardian);
  assert.ok(body.min.x>=support.min.x&&body.max.x<=support.max.x&&body.min.z>=support.min.z&&body.max.z<=support.max.z,'Statue extends past foundation');
  assert.ok(Math.abs(body.min.y-support.max.y)<1e-6,'Statue must sit flush on support');
  assert.ok(support.min.y<-2.1,'Support must reach below water');assert.ok(Math.min(Math.abs(support.min.x),Math.abs(support.max.x))>=8,'Shrine encroaches into water-side lane buffer');
 }
}
console.log('GROUNDING PASS: all12 statues fully supported and flush, foundations below water, varied distances');

assert.ok(batches.some(b=>b.geometry.userData.architecture==='beveled-temple-stone'),'Hero columns need actual beveled geometry');assert.equal(receipt.towerGeometry,'beveled-stone-recessed-relief-panels');
