import * as THREE from '../crown-pepe-3d/vendor/three.module.js';
import {createTempleWorld} from './temple-world.js';
import assert from 'node:assert/strict';
class TextureLoader{load(path,onLoad){const texture=new THREE.Texture();onLoad(texture);return texture;}}
const scene=new THREE.Scene(),world=createTempleWorld({...THREE,TextureLoader},scene),d={state:'running',distance:390,time:12};
const original=JSON.stringify(d);world.update(d,{active:false,player:{x:0,z:0}});assert.equal(JSON.stringify(d),original,'World mutated simulation');
const root=scene.children.find(o=>o.name==='Temple360World'),sky=root.children.find(o=>o.name==='TempleFullSphereSky'),batches=root.children.filter(o=>o.isInstancedMesh),receipt=world.diagnostics();
assert.equal(receipt.full3D,true);assert.equal(receipt.panorama,false);assert.ok(receipt.parts<2000);assert.ok(receipt.drawBatches<=32);assert.equal(receipt.chapter.name,'Canopy Corridor');assert.equal(receipt.highCanopies,8);assert.equal(receipt.skyRadius,180);assert.equal(sky.material.side,THREE.BackSide);assert.equal(sky.material.depthWrite,false);assert.equal(sky.material.fog,false);assert.equal(sky.castShadow,false);assert.equal(sky.geometry.parameters.phiLength,Math.PI*2);assert.equal(sky.geometry.parameters.thetaLength,Math.PI);assert.equal(receipt.trees,64);assert.equal(receipt.waterfalls,4);assert.equal(receipt.ferns,24);assert.equal(receipt.canopyGeometry,'curved-individual-fronds');assert.equal(receipt.sprayPoints,144);
assert.equal(receipt.assetsReady,true);assert.equal(receipt.error,null);
assert.equal(receipt.skyDistantLayers,3);assert.equal(receipt.skyRidgeMaxElevation,.10);const distantShader=sky.material.fragmentShader.slice(sky.material.fragmentShader.indexOf('vec3 distantHorizon'),sky.material.fragmentShader.indexOf('void main()'));assert.ok(distantShader.includes('layer<3'));assert.ok(distantShader.includes('direction.xz'),'Ridges are not fixed in world sky direction');assert.ok(!distantShader.includes('simulationTime'),'Distant mountains drift with simulation time');assert.ok(distantShader.includes('smoothstep(.085,.10,direction.y)'),'Ridges spill into upper sky');assert.ok(sky.material.fragmentShader.includes('color=distantHorizon(d,color)'),'Ridge function is unused');
assert.equal(receipt.gorgePillars,'tapered-chamfer-grounded');const pillar=batches.find(b=>b.geometry.userData.architecture==='tapered-chamfer-gorge-pillar');assert.ok(pillar);assert.equal(pillar.count,8);const pp=pillar.geometry.attributes.position;assert.equal(pp.count,24);assert.equal(pillar.geometry.attributes.uv.count,24);assert.ok(Math.abs(pp.getX(8))<Math.abs(pp.getX(0)),'Gorge pillar lacks taper');assert.ok(Math.abs(pp.getX(16))>Math.abs(pp.getX(8)),'Gorge pillar lacks flared capital');assert.equal(pp.getY(0),-.5);assert.equal(pp.getY(16),.5);for(let i=0;i<pp.count;i++)assert.ok(Math.abs(new THREE.Vector3().fromBufferAttribute(pillar.geometry.attributes.normal,i).length()-1)<1e-6,'Pillar normal invalid');
assert.equal(receipt.gorgeArchRise,3.2);const archCurve=batches.find(b=>b.geometry.userData.architecture==='curved-chamfered-gorge-lintel').geometry.attributes.position,curveCrown=[],curveEnds=[];for(let i=0;i<archCurve.count;i++){if(Math.abs(archCurve.getX(i))<.01)curveCrown.push(archCurve.getY(i));if(Math.abs(archCurve.getX(i))>.49)curveEnds.push(archCurve.getY(i));}assert.ok(Math.max(...curveCrown)-Math.max(...curveEnds)>1.9,'Distant arch curve remains imperceptible');assert.ok(Math.min(...curveEnds)<-.49&&Math.max(...curveEnds)>.4,'Arch endpoints no longer join grounded columns');
assert.equal(receipt.gorgeLintel,'curved-chamfered-stone');const lintel=batches.find(b=>b.geometry.userData.architecture==='curved-chamfered-gorge-lintel');assert.ok(lintel);assert.equal(lintel.count,4);const lp=lintel.geometry.attributes.position;assert.equal(lintel.geometry.attributes.uv.count,lp.count);const centerBottom=[],edgeBottom=[];for(let i=0;i<lp.count;i++){assert.ok(Math.abs(new THREE.Vector3().fromBufferAttribute(lintel.geometry.attributes.normal,i).length()-1)<1e-5,'Lintel has degenerate normals');if(lp.getY(i)<0){if(Math.abs(lp.getX(i))<.05)centerBottom.push(lp.getY(i));if(Math.abs(lp.getX(i))>.47)edgeBottom.push(lp.getY(i));}}assert.ok(Math.min(...centerBottom)>Math.min(...edgeBottom)+.12,'Lintel underside remains rectangular');assert.ok(Array.from(lp.array).some((v,i)=>i%3===2&&Math.abs(v)>.46&&Math.abs(v)<.5),'Lintel lacks actual edge chamfer');
assert.equal(receipt.gorgeFraming,'far-pair-portrait-visible');const portrait=new THREE.PerspectiveCamera(60,390/844,.1,450);portrait.position.set(0,4.6,9.5);portrait.lookAt(0,2.2,-12);portrait.updateMatrixWorld(true);for(const landmark of root.children.filter(g=>g.isGroup&&Math.abs(g.position.x)===24&&g.position.z===-124)){const center=new THREE.Vector3(landmark.position.x,40,landmark.position.z).project(portrait);assert.ok(Math.abs(center.x)<.9&&Math.abs(center.y)<.9,'Far gorge landmark remains cropped in portrait');const widest=new THREE.Vector3(landmark.position.x+Math.sign(landmark.position.x)*5.75,36,landmark.position.z).project(portrait);assert.ok(Math.abs(widest.x)<1,'Outer gorge frame disappears off portrait');}
assert.equal(receipt.gorgeLandmarkHeight,36);for(const landmark of root.children.filter(g=>g.userData.gorgeSkyLandmark)){const columns=landmark.children.filter(o=>o.userData.groundedGorgeColumn);assert.equal(columns.length,2);for(const column of columns){assert.equal(column.position.y-column.scale.y*.5,0,'Tall gorge column floats above shore');assert.equal(column.position.y+column.scale.y*.5,36);}const projectedTop=new THREE.Vector3(landmark.position.x,40,landmark.position.z).project(portrait);const templeRoof=new THREE.Vector3(Math.sign(landmark.position.x)*10,20,-62).project(portrait);assert.ok(projectedTop.y>templeRoof.y+.03,'Far gorge arch stays hidden behind temple tower');}
const roofMaterial=batches.find(o=>o.material.userData.surface==='weathered-pagoda-stone').material,roughPixels=roofMaterial.roughnessMap.image.data,effectiveRoughness=[];for(let i=1;i<roughPixels.length;i+=4)effectiveRoughness.push(roughPixels[i]/255*roofMaterial.roughness);assert.ok(Math.min(...effectiveRoughness)>.92,'Roof map multiplies roughness down into glossy range');assert.ok(Math.max(...effectiveRoughness)-Math.min(...effectiveRoughness)>.01,'Matte roof lost restrained roughness variation');const rockMap=batches.find(o=>o.material.roughnessMap&&o.material!==roofMaterial).material.roughnessMap;assert.notEqual(roofMaterial.roughnessMap,rockMap,'Roof matte tuning mutates shared stone');assert.ok(Math.min(...rockMap.image.data.filter((_,i)=>i%4===1))<230,'Shared nonroof roughness changed');
assert.equal(receipt.roofSurface,'weathered-pagoda-stone');const roofStoneBatch=batches.find(o=>o.material.userData.surface==='weathered-pagoda-stone');assert.ok(roofStoneBatch);assert.ok(roofStoneBatch.material.bumpMap&&roofStoneBatch.material.roughnessMap&&roofStoneBatch.material.map,'Roof weathered stone maps unavailable');assert.equal(roofStoneBatch.material.bumpScale,.10);assert.equal(roofStoneBatch.material.roughness,.96);assert.equal(roofStoneBatch.material.metalness,0);assert.equal(roofStoneBatch.material.map.wrapS,THREE.RepeatWrapping);assert.ok(roofStoneBatch.material.map.repeat.x>=2);assert.equal(roofStoneBatch.material.vertexColors,false);
assert.equal(receipt.pagodaEaves,'closed-depth-varied-tier-pitch');const solidRoof=batches.find(b=>b.geometry.userData.solidEaveDepth).geometry;assert.equal(solidRoof.attributes.position.count,60);assert.ok(Math.abs(solidRoof.attributes.position.getY(25)-solidRoof.attributes.position.getY(55)-.09)<1e-6,'Roof eaves remain paper thin');assert.equal(solidRoof.index.count,264,'Roof lacks underside and edge faces');const tiers=[];root.traverse(o=>{if(o.userData.pagodaTier)tiers.push(o);});assert.equal(tiers.length,12);assert.ok(new Set(tiers.map(o=>o.scale.y.toFixed(2))).size>=4,'Pagoda pitches remain repeated shallow pyramids');assert.ok(tiers.every(o=>o.scale.y>=2.3),'Roof sculptural depth too shallow');
assert.equal(receipt.cliffProfiles,2);const cleft=batches.find(o=>o.geometry.userData.formation==='cleft-diagonal-rock-cap');assert.ok(cleft&&cleft.count>10,'Cleft cap profile unused');const primary=batches.find(o=>o.geometry.userData.formation==='fractured-asymmetric-rock-strata');assert.notDeepEqual(Array.from(cleft.geometry.attributes.position.array),Array.from(primary.geometry.attributes.position.array),'Rock profiles are identical');let cutDepth=0;for(let i=0;i<cleft.geometry.attributes.position.count;i++){cutDepth=Math.max(cutDepth,primary.geometry.attributes.position.getY(i)-cleft.geometry.attributes.position.getY(i));assert.ok(Math.abs(new THREE.Vector3().fromBufferAttribute(cleft.geometry.attributes.normal,i).length()-1)<1e-5,'Cleft normals are degenerate');}assert.ok(cutDepth>.2,'Cap has no carved profile cleft');assert.equal(cleft.geometry.attributes.uv.count,primary.geometry.attributes.uv.count);
assert.equal(receipt.cliffGeometry,'fractured-asymmetric-rock-strata');const fractured=batches.find(o=>o.geometry.userData.formation==='fractured-asymmetric-rock-strata').geometry,fracturedPosition=fractured.attributes.position;assert.equal(fractured.attributes.uv.count,fracturedPosition.count);const radii=[];for(let i=0;i<fracturedPosition.count;i++){radii.push(new THREE.Vector3().fromBufferAttribute(fracturedPosition,i).length());assert.ok(Math.abs(new THREE.Vector3().fromBufferAttribute(fractured.attributes.normal,i).length()-1)<1e-5,'Fractured rock normals are degenerate');}assert.ok(Math.max(...radii)-Math.min(...radii)>.25,'Rock retains spherical pillow shape');assert.ok(fracturedPosition.getY(0)!==-fracturedPosition.getY(1),'Cliff strata remain symmetric');assert.ok(fractured.boundingBox.max.y<1.04&&fractured.boundingBox.min.y<-.8,'Rock lacks stepped upper profile and deep lower face');
assert.equal(receipt.roofGeometry,'upturned-four-sided-pagoda');assert.equal(receipt.skyAtmosphere,'layered-horizon-cloud-depth');const curvedRoof=batches.find(b=>b.geometry.userData.architecture==='upturned-four-sided-pagoda');assert.ok(curvedRoof);const roofPositions=curvedRoof.geometry.attributes.position;assert.ok(roofPositions.getY(25)>roofPositions.getY(20)+.09,'Eaves are not physically upturned');assert.ok(roofPositions.getY(0)>roofPositions.getY(20),'Roof has no falling pitch');assert.equal(curvedRoof.geometry.attributes.uv.count,roofPositions.count);for(let i=0;i<roofPositions.count;i++)assert.ok(new THREE.Vector3().fromBufferAttribute(curvedRoof.geometry.attributes.normal,i).length()>.9,'Roof has degenerate normals');
assert.equal(receipt.organicTrunks,true);const modeledTrees=root.children.filter(g=>Number.isFinite(g.userData.initialX));assert.equal(modeledTrees.length,64);for(const tree of modeledTrees){const stems=tree.children.slice(0,3);assert.ok(stems.every(m=>m.geometry.type==='CylinderGeometry'));assert.ok(stems[0].scale.x>stems[1].scale.x&&stems[1].scale.x>stems[2].scale.x,'Trunk does not taper');for(let i=0;i<2;i++){const end=new THREE.Vector3(0,.5,0).applyMatrix4(stems[i].matrix),start=new THREE.Vector3(0,-.5,0).applyMatrix4(stems[i+1].matrix);assert.ok(end.distanceTo(start)<1e-6,'Trunk segment joins disconnect');}assert.equal(tree.children.filter(m=>m.geometry?.type==='TubeGeometry').length,2);assert.equal(tree.userData.vines.length,4);}
const supportedCanopies=root.children.filter(o=>o.userData.supports);assert.equal(supportedCanopies.length,8);
assert.equal(receipt.understoryGeometry,'grounded-asymmetric-six-frond-clusters');const understory=root.children.filter(g=>g.userData.understory);assert.equal(understory.length,24);const fernFronds=understory.flatMap(g=>g.children);assert.equal(fernFronds.length,144);assert.ok(new Set(fernFronds.map(o=>o.rotation.x.toFixed(3))).size>80,'Understory has repeated height tiers');for(const plant of understory){assert.equal(plant.position.y,.015,'Fern crown floats above shore');for(const leaf of plant.children){const bounds=new THREE.Box3().setFromObject(leaf);for(let vertex=0;vertex<leaf.geometry.attributes.position.count;vertex++)assert.ok(new THREE.Vector3().fromBufferAttribute(leaf.geometry.attributes.position,vertex).applyMatrix4(leaf.matrixWorld).y>-.01,'Fern sinks through terrain');assert.ok(Math.min(Math.abs(bounds.min.x),Math.abs(bounds.max.x))>=18,'Fern intrudes across bank corridor');assert.ok(leaf.position.length()===0,'Fern leaves detach from rooted crown');}}
assert.equal(receipt.crownDistribution,'asymmetric-spiral-varied-tilt');
const crownFronds=modeledTrees.flatMap(g=>g.children.filter(o=>o.userData.crownFrond));assert.equal(crownFronds.length,768);
assert.ok(new Set(crownFronds.map(o=>o.rotation.x.toFixed(3))).size>100,'Tree leaf tilt remains repeated shelves');assert.ok(new Set(crownFronds.map(o=>o.rotation.z.toFixed(3))).size>100,'Tree leaves lack varied roll');assert.ok(Math.max(...crownFronds.map(o=>o.scale.x))-Math.min(...crownFronds.map(o=>o.scale.x))>.8,'Crown frond scale remains uniform');
for(const tree of modeledTrees){const leaves=tree.children.filter(o=>o.userData.crownFrond);assert.ok(Math.max(...leaves.map(o=>o.position.y))-Math.min(...leaves.map(o=>o.position.y))>1,'Crown still stacks in uniform tiers');}
assert.equal(receipt.canopySupports,'curved-endpoint-aligned-boughs');
assert.equal(receipt.canopyComposition,'asymmetric-side-branch-clusters');
const clusteredLeaves=supportedCanopies.flatMap(g=>g.children.filter(o=>o.geometry?.attributes.position.count===85));assert.equal(clusteredLeaves.length,48,'Canopy composition added instances');
assert.ok(new Set(clusteredLeaves.map(o=>o.rotation.y.toFixed(3))).size>20,'Fronds repeat uniform angles');assert.ok(new Set(supportedCanopies.flatMap(g=>g.userData.supports.map(s=>s.attachment.toArray().join(',')))).size>8,'Branch joins repeat uniform attachments');
const compositionSnapshot=clusteredLeaves.map(o=>o.matrix.toArray());world.update(d,{active:false,player:{x:0,z:0}});assert.deepEqual(clusteredLeaves.map(o=>o.matrix.toArray()),compositionSnapshot,'Composition drifts at frozen simulation time');
for(const canopy of supportedCanopies)for(const {side,stem,limb,attachment} of canopy.userData.supports){
  assert.equal(limb.geometry.type,'TubeGeometry');const path=limb.geometry.parameters.path;
  const start=path.getPoint(0),end=path.getPoint(1),middle=path.getPoint(.5);
  assert.ok(middle.distanceTo(start.clone().lerp(end,.5))>.1,'Support is still a straight scaffold');
  assert.ok(start.clone().applyMatrix4(limb.matrix).distanceTo(new THREE.Vector3(stem.position.x,15.6,0))<1e-6,'Branch disconnects from trunk');
  assert.ok(end.clone().applyMatrix4(limb.matrix).distanceTo(attachment)<1e-6,'Branch disconnects from canopy');
}
function assertCanopyClearance(){root.updateMatrixWorld(true);for(const canopy of supportedCanopies){for(const {stem,limb,attachment} of canopy.userData.supports){const stemBounds=new THREE.Box3().setFromObject(stem),limbBounds=new THREE.Box3().setFromObject(limb);assert.ok(Math.abs(attachment.x)>=12,'Branch join spans central opening');assert.ok(Math.min(Math.abs(stemBounds.min.x),Math.abs(stemBounds.max.x))>=18,'Canopy trunk intrudes in corridor');assert.ok(limbBounds.min.y>=14,'Canopy limb hangs across arch face');assert.ok(Math.min(Math.abs(limbBounds.min.x),Math.abs(limbBounds.max.x))>=12,'Bough crosses center sightline');}for(const leaf of canopy.children.filter(o=>o.geometry?.type==='BufferGeometry')){const bounds=new THREE.Box3().setFromObject(leaf);assert.ok(bounds.min.y>=18,'Canopy leaf covers raised frog eyes');assert.ok(Math.min(Math.abs(bounds.min.x),Math.abs(bounds.max.x))>=12,'Leaf spans center opening');}}}
assertCanopyClearance();assert.ok(root.children.some(g=>g.isGroup&&Math.abs(g.position.x)===24&&g.position.z===-78),'Mobile courtyard landmark missing');assert.ok(root.children.some(g=>g.isGroup&&Math.abs(g.position.x)===24&&g.position.z===-124),'Mobile gorge landmark missing');assert.ok(root.children.some(g=>g.isGroup&&Math.abs(g.position.x)===33&&g.position.z===-38),'Waterfall framing arch removed');
assert.equal(receipt.shoreGeometry,'solid-irregular-water-contact');const shore=root.children.filter(o=>o.userData.shoreBank);assert.equal(shore.length,2);for(const bank of shore){const bounds=new THREE.Box3().setFromObject(bank);assert.ok(Math.abs(bounds.max.y)<1e-6,'Shore no longer grounds roots at zero');assert.ok(bounds.min.y<-.49,'Bank lacks solid water-contact depth');assert.ok(Math.min(Math.abs(bounds.min.x),Math.abs(bounds.max.x))>=18,'Shore encroaches on playable corridor');const p=bank.geometry.attributes.position,edge=[];for(let i=0;i<p.count;i++)if(p.getX(i)<0)edge.push(p.getX(i));assert.ok(Math.max(...edge)-Math.min(...edge)>1,'Waterline edge remains straight');assert.ok(Math.max(...edge)<-80,'Irregular shore removes fern support');}
for(const fern of understory)assert.ok(Math.abs(fern.position.x)>20&&Math.abs(fern.position.z)<175,'Fern crown lost solid bank support');
for(const cliff of root.children.filter(o=>o.geometry?.type==='IcosahedronGeometry'&&o.scale.z>=9&&o.scale.x>=7))assert.ok(!(Math.abs(cliff.position.x)<18&&cliff.position.z<0),'Front center ridge still blocks arch corridor');
for(const cliff of root.children.filter(o=>o.geometry?.userData.formation&&o.position.z<0)){const bounds=new THREE.Box3().setFromObject(cliff);assert.ok(bounds.min.x>=18||bounds.max.x<=-18,'Actual fractured cliff bounds intrude into frog arch opening');}
assert.equal(batches.reduce((n,b)=>n+b.count,0)+receipt.waterfalls+1,receipt.parts);assert.equal(batches.length+receipt.waterfalls+5,receipt.drawBatches);
const sprays=[];root.traverse(o=>{if(o.isPoints)sprays.push(o);});assert.equal(sprays.length,4);for(const spray of sprays){assert.equal(spray.geometry.attributes.position.count,36);assert.equal(spray.material.fog,true);assert.equal(spray.material.uniforms.simulationTime.value,d.time);}
assert.equal(receipt.mistGeometry,'local-soft-age-faded-base-puffs');assert.equal(receipt.mistOpacity,.26);for(const spray of sprays){assert.equal(spray.material.depthWrite,false);assert.equal(spray.material.uniforms.mistLift.value,1.15);assert.ok(spray.material.vertexShader.includes('modelViewMatrix*vec4(p,1.)'),'Mist loses local temple heading');assert.ok(spray.material.fragmentShader.includes('smoothstep(0.,.16,particleAge)'),'Mist spawns as hard dots');for(let i=0;i<36;i++){const p=new THREE.Vector3().fromBufferAttribute(spray.geometry.attributes.position,i);assert.ok(Math.abs(p.x)<=1.200001&&Math.abs(p.z)<=.600001&&p.y<.13,'Mist base escapes waterfall footprint');}assert.ok(Math.abs(spray.parent.position.x)>=32,'Mist intrudes in route');}
const frondBatch=batches.find(b=>b.geometry.type==='BufferGeometry'&&b.geometry.attributes.position.count===85);assert.ok(frondBatch);assert.ok([...frondBatch.geometry.attributes.position.array].some((v,i)=>i%3===1&&v>0),'Leaf geometry has no actual curvature');
const volume=frondBatch.geometry.attributes.position;assert.ok(volume.getY(40)>volume.getY(41)+.09,'Leaf edge has no sculpted cup');assert.ok(volume.getY(82)>.19,'Leaf tip lacks substantial curl');assert.ok(Math.max(...Array.from({length:85},(_,i)=>volume.getY(i)))>.45,'Leaf remains a thin flat sheet');for(let i=0;i<85;i++){const normal=new THREE.Vector3().fromBufferAttribute(frondBatch.geometry.attributes.normal,i);assert.ok(Math.abs(normal.length()-1)<1e-5,'Sculpted leaf normals are not unit length');}assert.ok(Math.abs(volume.getX(40)+volume.getX(44)-2*volume.getX(42))>.01,'Leaf edge is perfectly mirrored');
assert.equal(frondBatch.material.vertexColors,true);const frond=frondBatch.geometry;assert.equal(frond.attributes.uv.count,frond.attributes.position.count);assert.equal(frond.attributes.color.count,frond.attributes.position.count);assert.ok([...frond.attributes.uv.array].every(v=>v>=0&&v<=1));assert.ok(Math.max(...frond.attributes.color.array)-Math.min(...frond.attributes.color.array)>.1,'Leaf variegation is uniform');const widthAt=row=>(frond.attributes.position.getX(row*5+4)-frond.attributes.position.getX(row*5))/2;assert.ok(widthAt(5)>widthAt(4)&&widthAt(5)>widthAt(6),'Leaf edge has no modeled lobe');assert.ok(frond.attributes.position.getY(42)>frond.attributes.position.getY(41)+.02,'Central rib has no raised geometry');assert.ok(frond.attributes.position.getY(82)>.08,'Leaf tip has no curl');
const detailedRock=batches.find(b=>b.material.bumpScale===.12);assert.ok(detailedRock);assert.equal(detailedRock.material.bumpMap.isDataTexture,true);assert.equal(detailedRock.material.roughnessMap.isDataTexture,true);
assert.equal(frondBatch.material.side,THREE.DoubleSide);for(let i=0;i<frondBatch.geometry.attributes.normal.count;i++){const normal=new THREE.Vector3().fromBufferAttribute(frondBatch.geometry.attributes.normal,i);assert.ok(normal.length()>.9,'Leaf has collapsed tip normals');}assert.ok(frondBatch.material.emissiveIntensity>=.35);
assert.equal(receipt.foliageFlutter,true);assert.equal(receipt.flutterTime,d.time);assert.equal(receipt.flutterShadow,'matching-depth-shader');assert.equal(receipt.waterfallGeometry,'layered-noise-turbulent-flow-foam');assert.ok(frondBatch.customDepthMaterial);assert.equal(frondBatch.customDepthMaterial.userData.foliageTime,frondBatch.material.userData.foliageTime);const visibleShader={vertexShader:THREE.ShaderLib.standard.vertexShader,uniforms:{}},shadowShader={vertexShader:THREE.ShaderLib.depth.vertexShader,uniforms:{}};frondBatch.material.onBeforeCompile(visibleShader);frondBatch.customDepthMaterial.onBeforeCompile(shadowShader);assert.equal(visibleShader.uniforms.foliageTime,shadowShader.uniforms.foliageTime);assert.equal(visibleShader.uniforms.foliageTime.value,d.time);
const freeze=()=>({receipt:world.diagnostics(),instances:batches.map(b=>Array.from(b.instanceMatrix.array)),root:root.matrixWorld.toArray(),flutterTime:visibleShader.uniforms.foliageTime.value,shadowFlutterTime:shadowShader.uniforms.foliageTime.value,skyTime:sky.material.uniforms.simulationTime.value,skyNight:sky.material.uniforms.night.value,skyGorge:sky.material.uniforms.gorge.value,sprayTime:sprays.map(s=>s.material.uniforms.simulationTime.value)});const frozen=freeze();for(let i=0;i<20;i++)world.update(d,{active:false,player:{x:0,z:0}});assert.deepEqual(freeze(),frozen,'Pause changed world or sky/spray/flutter');
world.update(d,{active:true,nextHeadingYaw:Math.PI/2,player:{x:-3,z:0}});assert.equal(root.rotation.y,Math.PI/2);assert.equal(root.position.x,-3);const ahead=new THREE.Vector3(0,0,-60).applyMatrix4(root.matrixWorld);assert.ok(ahead.x<-3&&Math.abs(ahead.z)<1e-7,'World failed to turn into outgoing road');
const activeFrozen=freeze();world.update(d,{active:true,nextHeadingYaw:Math.PI/2,player:{x:-3,z:0}});assert.deepEqual(freeze(),activeFrozen,'Paused turn changed world');
d.distance=550;d.time=20;world.update(d,{active:false,player:{x:0,z:0}});assert.equal(world.diagnostics().night,1);assert.equal(world.diagnostics().waterfallTime,20);assert.equal(world.diagnostics().sprayTime,20);assert.equal(sky.material.uniforms.simulationTime.value,20);assert.equal(root.rotation.y,0);assert.notDeepEqual(batches.map(b=>Array.from(b.instanceMatrix.array)),frozen.instances,'Advancing world has no depth parallax');
assert.ok(frondBatch.material.emissiveIntensity>=.2&&frondBatch.material.emissiveIntensity<.3,'Night leaf emission exceeds restrained range');
assert.equal(world.diagnostics().chapter.name,'Sunken Ruined Courtyard');assert.equal(world.diagnostics().chapter.courtyardBlend,1);d.distance=1010;world.update(d);assert.equal(world.diagnostics().chapter.name,'Waterfall Gorge');assert.ok(world.diagnostics().chapter.gorgeBlend>0&&world.diagnostics().chapter.gorgeBlend<1);d.distance=1100;world.update(d);assert.equal(world.diagnostics().chapter.gorgeBlend,1);const chapterFreeze=freeze();world.update(d);assert.deepEqual(freeze(),chapterFreeze,'Paused chapter altered composition');
for(const landmark of root.children.filter(g=>g.isGroup&&Math.abs(g.position.x)===24&&g.position.z===-124)){const bounds=new THREE.Box3().setFromObject(landmark);assert.ok(bounds.min.x>=18||bounds.max.x<=-18,'Gorge framing enters corridor when fully expanded');}
assertCanopyClearance();
class FailedTextureLoader{load(path,onLoad,onProgress,onError){onError(new Error('fixture'));return new THREE.Texture();}}
const fallback=createTempleWorld({...THREE,TextureLoader:FailedTextureLoader},new THREE.Scene());fallback.update(d);assert.equal(fallback.diagnostics().loaded,true);assert.equal(fallback.diagnostics().assetsReady,false);assert.ok(fallback.diagnostics().error.includes('material colors'));
console.log(`WORLD PASS: full-sphere sky and modeled360 world, ${receipt.parts} parts/${receipt.drawBatches} batches, read-only simulation, pause, turn transform, night, waterfall time, parallax`);
